### ISSUE TITLE
Published 2.0 XSD and examples are actually for 1.0

### ISSUE THREAD

**Issue by haudiobe** [Dash-Industry-Forum/CPIX#10]
Submitter: Maxim Shevchenko
Schema and examples provided together with CPIX 2.0 spec are actually for CPIX 1.0.
http://dashif.org/wp-content/uploads/2016/11/Schema-Examples-v2.0.zip

Old schema is more up to date that the new one:
http://dashif.org/wp-content/uploads/2016/07/Schema-Examples-v1.91.zip

**Comment by sandersaares** [comment]
Ouch, how did we miss this!

**Comment by lpiron** [comment]
DASH-IF site is OK, it references http://dashif.org/wp-content/uploads/2016/11/Schema-Examples-v2.01.zip which is the correct file. Nevertheless, the wrong file is still available and can be accessed if the exact URL is available.
Closed as the wrong file cannot be deleted from the system

**Comment by sandersaares** [comment]
The problem remains.

From http://dashif.org/guidelines/ you are linked to http://dashif.org/wp-content/uploads/2016/11/DASH-IF-CPIX-v2-0.pdf which on page 5 links you to the wrong URL. We need to replace this main CPIX PDF.

**Comment by lpiron** [comment]
Never ending story. Thanks for pointing it out. I will create a new version with a link to http://dashif.org/guidelines/ where the examples are available instead of a specific file. It is very likely that a specific link will create issues in further version (not updated in the document)

**Comment by lpiron** [comment]
Corrected. File deleted and new CPIX PDF with an updated reference
