### ISSUE TITLE
ContentKeyPeriod range for VOD

### ISSUE THREAD

**Issue by brateme** [Dash-Industry-Forum/CPIX#100]
The `start`/`end` attributes of `ContentKeyPeriod` are defined for VOD as "media time for the start/end time for the period".
However, the value is a date (`xs:dateTime`) and there is no instructions on how to map date values to media times.
As a result, there is no portable way to use those attributes for VOD.

I can think of three possibilities to solve this issue.
- Add new dedicated attributes for VOD (e.g. `startOffset`/`endOffset`), with their own type.
- Change the type and definition of `start`/`end` to be either `xs:dateTime` for live or `xs:duration` (or `xs:time`) for VOD.
- Define an epoch to be used to map dates to VOD offsets (e.g. start of VOD asset is mapped to UNIX epoch).

IMHO, first option is the cleanest.

**Comment by lpiron** [comment]
Would like to avoid touching existing stuff.
Either add a new element for VOD or new elements (optional) under ContentKeyPeriod

**Comment by lpiron** [comment]
New attributes added in CPIX 2.4
