### ISSUE TITLE
Attribute end of ContentKeyPeriod tag must be optional

### ISSUE THREAD

**Issue by sanao** [Dash-Industry-Forum/CPIX#101]
The attribute `end` of `ContentKeyPeriod` tag must be optional because in some cases, we don't know when a period ends. And currently, the specification say `start` attribute is mutually inclusive with `end` attribute.

**Comment by sanao** [comment]
Any news?

**Comment by lpiron** [comment]
We discussed this during the call today. Next version of CPIX will be corrected accordingly. The `end` tag will be optional.
