### ISSUE TITLE
Unique system identifier for CPIX

### ISSUE THREAD

**Issue by haudiobe** [Dash-Industry-Forum/CPIX#105]
Based on [MPEG Liaison](https://members.dashif.org/wg/Liaison/document/4747), we ask for the following:

MPEG has included the DASH-IF’s CPIX format in their REAP Working Draft and are interested to get our feedback including potentially defining a unique system identifier for CPIX for signaling in I-MPD. Registration of a UUID for CPIX would be needed. 

WG03N0722, Working Draft of ISO/IEC 23009-9 Redundant encoding and packaging for segmented live media (REAP), which was previously called encoder and packager synchronization

**Comment by RufaelDev** [comment]
Correct, 
the idea is to be able to signal CPIX in the MPD, 
current text in the working draft states the following:

9.	In the case an AdaptationSet signals encrypted tracks, the ContentProtection element shall be present with the following constraints:
i.	The dashif:Laurl element shall be present in the ContentProtection element and contain a URL of a license server. The authentication server shall not be used.
ii.	The URL of the license server shall start with https:// and should use mutually authenticated TLS for the purpose. In this case the value of dashif:Laurl.licenseType shall include the string “mtls” 
iii.	A response of the license server should be a valid CPIX document.
iv.	In case both decryption and encryption are needed, the value of dashif:Laurl.licenseType used for decryption shall include the string “decrypt”.

It would be useful to get the opinion of the cps group on the idea of signalling cpix as a DRM. 
Then a second step could be that either MPEG or DASH-IF defines a system id for this.

**Comment by lpiron** [comment]
This looks like a valid approach, Few questions/comments
- Does disabling the authentication server URL means that there is no token/no authentication for accessing the license server ? Note that having HTTPS will not really restrict access to this endpoint if this is widely visible.
- I do not understand the use of `@licenseType`. If mutual authentication with HTTPS is required, I'm not sure I understand why this is announced in the `@licenseType`, as this is not a "license type" and this is part of the TLS protocol where the server will request the client certificate, if the client does not provide it, the TLS session is not initiated.
- There may be some need for extra information on what a "valid CPIX document" is. There are few optional parameters in CPIX, maybe you should streamline it. Is the encryption of the content key needed? Is a CPIX document signed? If both are "no", then maybe a simple ClearKey approach (W3C spec) would be enough.
- I do not understand the last point (iv). What will be the `@licenseType` if mixing (ii) and (iv) ? Does it has an impact on the license request ?

**Comment by RufaelDev** [comment]
@lpiron thank you for the feedback i drafted a potential response on this and uploaded it on causeway: https://members.dashif.org/wg/CPS/document/4750

**Comment by lpiron** [comment]
Closing as MPEG meeting dealing with this happened in January.
