### ISSUE TITLE
ContentKeyPeriod - no need for mutual exclusivity between start/end and index

### ISSUE THREAD

**Issue by melads** [Dash-Industry-Forum/CPIX#108]
Hi, 
The current CPIX spec defines mutual exclusivity between ContentKeyPeriod@start/end and ContentKeyPeriod@index.
This mutual exclusivity creates situations where encryptor and DRM systems need to have an out-of-band agreement on how to convert crypto period index to absolute time.
In order to avoid that, I suggest to allow sending both index and start/end attributes in the same ContentKeyPeriod item, and remove the mutual exclusivity constraint.

**Comment by lpiron** [comment]
Adressed with CPIX 2.4
