### ISSUE TITLE
Explicitly link requested keys to policies

### ISSUE THREAD

**Issue by haudiobe** [Dash-Industry-Forum/CPIX#11]
Submitter: Maxim Shevchenko
There is no way in current CPIX model to explicitly link requested keys to a policies defined on the DRM server:
E.g. in the Encryptor Consumer when there is no DRM signaling provided to the DRM server, encoder ask to generate keys for the multiple tracks: sd, hd, uhd. DRM Server has different policies associated to each track types (e.g give hd and uhd only to devices with HDCP 2.1).

In current spec there is no way to make this in a explicit way. Only way that I found is implicit through @id of the Content Key.

It will be great to have explicit TrackType property in the document that will define where a key is intended to be used.

**Comment by sandersaares** [comment]
Seems roughly equivalent to https://github.com/Dash-Industry-Forum/CPIX/issues/13

By providing license server with the CPIX describing the content and the names of the content key contexts to authorize, business logic can apply arbitrary policies.

**Comment by lpiron** [comment]
This bug is closed with no action and no update to the specification. Explanation were given for handling it and no further action was requested.
