### ISSUE TITLE
Maintain CPIX XML Schema on GitHub

### ISSUE THREAD

**Issue by sandersaares** [Dash-Industry-Forum/CPIX#14]
I propose that we maintain the XML Schema on GitHub, in the Git repository that we have here (currently empty). This allows for easy history, pull requests and whatnot. Granted, it is not a document that sees heavy editing but it seems beneficial to introduce some modern distributed document editing practices somehow. The XML Schema seems like the minimally useful set to start with.

Assuming all editors are comfortable with it, of course. It does not seem important enough to be worth causing any extra effort for anyone given the expected low workload on CPIX.

(In long-term, I would also view positively the idea of maintaining the entire spec in a Git repository here, to be compiled to website/PDF via some tool such as DocFX or equivalent.)

**Comment by lpiron** [comment]
Agreed. We will move the schema to Github once it is updated. This bug is left open until the schema is on Github.

**Comment by lpiron** [comment]
The schema has been added in the community review branch
