### ISSUE TITLE
Include key hierarchies in CPIX scope

### ISSUE THREAD

**Issue by sandersaares** [Dash-Industry-Forum/CPIX#17]
What are key hierarchies?
====================

Modern DRM systems support key hierarchies, where you have two levels of keys being used:

1. Leaf keys used to encrypt samples.
1. Root keys used to protect the media keys.

The meaning of "protect" here is DRM system specific. What matters is that the leaf keys cannot be used without having the root keys.

The DRM system on the client will obtain the protected leaf keys from PSSH boxes embedded in the media stream (in DRM-system-specific format) and use the root keys to "resolve" the DRM system specific protection (e.g. decrypt the leaf keys).

On the DASH and EME layer, all that is visible are the root keys, which are retrieved and signaled using the normal licence acquisition mechanisms.

Different DRM systems use different terms but the general idea is the same.

What do the workflows look like?
=======================

To create content using key hierarchices, a packager needs to know:

* The leaf keys (for encrypting samples).
* The PSSHs carrying the protected leaf keys (put into media segments). May be accompanied by key policy information for the DRM client.
* The root keys (signaled in manifest).
* The PSSHs signaling the use of the root keys (put into init segments).

For some scenarios, it may be sufficient to only know the key IDs of the root keys (and not the actual key data).

To generate such keys, a key server needs to know that it needs to generate a key hierarchy, and how many keys to generate of each type and how to relate them.

To grant licenses, a license server needs to know the root keys.

What is the problem?
==============

Currently, CPIX basically ignores the root keys, which seems to be needlessly limiting and requires proprietary protocols to be created in order to communicate key hierarchies between different endpoints. Quoting CPIX 2.0:

> Some key rotation implementations may store the Content Keys within the PSSH data. These
keys are usually wrapped (encrypted) with another key, which is delivered to the client as part
of the content license. This ‘root’ key should never be encoded in the CPIX document; instead
the CPIX document shall only contain the Content Keys in the ContentKey elements.

The last sentence there leaves key hierarchies strictly out of scope. Instead, CPIX should explicitly support signaling hierarchical keys to improve interoperability.

I will post my first thoughts on a solution as a comment below.

**Comment by sandersaares** [comment]
It seems to me that CPIX could support key hierarchices without much effort by allowing content keys to reference other content keys. The media keys could have some `@dependsOnContentKey="kid"` value that references another key in the same document. Hierarchy-aware packagers would look for this value and act accordingly.

**Comment by sandersaares** [comment]
While very simple to implement and minimally impactful specification-wise, the above proposal has the shortcoming that it does not make a significant distinction between root and leaf keys. It is not entirely clear what the potential consequences here might be but it feels more right to make a distinction as the two types of keys are really used in rather different ways.

An alternative implementation would be something like the following:

* A new top-level list to carry the root keys (naming is an issue - there really is no generic terminology we could use here!). In content, equivalent to content keys. Just used differently.
* References from content key to root key (`@dependsOnRootKey=rootKid` style).
* Signaling could perhaps remain unchanged? That is, DRM system signaling happens on the leaf key level, not the root key level - you put the leaf key PSSH in the media segment and the root key PSSH (in the DRMSystem element associated with the **leaf** key) in the MPD and use default_KID of the root key (dereferencing the reference on the content key). Not sure if this is generic enough, though.

Overall, this sounds like more complexity in the spec without actually adding more value, so I tend to prefer the simpler case of just treating key hierarchies as dependencies between content keys as far as CPIX is concerned. I would welcome additional insight, however, as I suspect I have not considered all the angles here.

**Comment by tinskip** [comment]
The key dependency works for me, as it is simple and efficient, but we need to call out the use cases for these keys (dependent or dependee) having or not having associated DRMSytem elements.

**Comment by sandersaares** [comment]
I will try to come up with some text.

**Comment by sandersaares** [comment]
Here's my attempt at some text.

I assume a max two level hierarchy (no intermediate keys - can extend later if truly needed but does not seem like a real world use case).

---

`@dependsOnRootKey`

Signals that the current Content Key is a leaf key in a key hierarchy. The value references the `@kid` attribute of another `ContentKey` element describing the root key.

The referenced key must not itself be a leaf key.

---

`DRMSystem/PSSH` updated to reflect PSSH handling for key hierarchy (also fixing https://github.com/Dash-Industry-Forum/CPIX/issues/21 at the same time), replacing existing text with the following.

This is the full PSSH box that should be added to ISOBMFF files encrypted with the referenced Content Key.

When the key is not part of a key hierarchy or is a root key in a key hierarchy, the value is inserted under the `moov` box.

When the key is a leaf key in a key hierarchy, the value is inserted under the `moof` boxes.

This element has meaning only when the media content is in the ISOBMFF format.

---

`DRMSystem/ContentProtectionData` updated to reflect MPD handling for key hierarchy, replacing existing text with the following.

This is the full XML element to be added to the DASH manifest under the `ContentProtection` element for this DRM system.

This element shall not be used if the referenced Content Key is a leaf key in a key hierarchy.

This element has meaning only when a DASH manifest is created for the media content.

---

Rename `4.1.2 Key Hierarchy in the CPIX Document` to `4.1.2 Keys used to secure the CPIX document` to avoid terminology issues. Also in figure 18.

---

Remove last paragraph of `4.2` (the one speaking about key hierarchies) and replace it with a new chapter:

4.3 Hierarchical Keys
============

Some DRM systems support the use of hierarchical keys, where the Content Keys used to encrypt media samples (leaf keys) are not usable without a second set of keys (root keys). The exact mechanism for combining leaf and root keys during cryptographic operations is DRM system specific and outside the scope of CPIX, which merely provides a mechanism for expressing such relationships.

CPIX supports expressing two-level key hierarchies, where each leaf key has exactly one root key that is required in order to use the leaf key. Both root keys and leaf keys are rerepsented using `ContentKey` elements, with leaf keys indicated by the presence of a `@dependsOnRootKey` reference to the root key.

When using hierarchical keys, only the leaf keys shall be used to encrypt media content. Therefore, root keys must not be referenced by any `ContentKeyUsageRule` elements.

The usage of DRM system signaling data is different when hierarchical keys are used. The differences are described in the documentation of the `DRMSystem` element.

**Comment by sandersaares** [comment]
A review in yesterday's CPS call identified multi-DRM interoperability as a point that needs further elaboration in this proposal.

Let's consider this from the viewpoint of existing DRM systems that support hierarchical keys (PlayReady and Widevine) and hypothetical future DRM systems that do so.

The key point of complexity is that there is no standard mechanism for creating keys in a key hierarchy - each DRM system can do it differently. For example:

* In case of Widevine, all keys (regardless of root or leaf) are independent and can be generated using natural means.
* In case of PlayReady, the root key is independent but leaf keys are derived from the root key using a fairly complex DRM system specific mechanism that can also take additional data as input for enabling some extra DRM system specific key management features.

There is no "natural" compatibility between the two schemes - if you have a key hierarchy for one, that hierarchy will not necessarily work for the other if the latter sets specific requirements on the keys. As I understand it, an implementation today could "force" it to be compatible deliberately thanks do Widevine treating keys as independent - you just generate a PlayReady key hierarchy and reuse the same keys for Widevine. However, this is more of a coincidence and as no standard for creating key hierarchies exists, it does not make a good foundation for specifying anything.

For any DRM system interoperability to exist, the leaf keys must be identical, as those are used to actually encrypt content. It is up to the provider of the key hierarchy to figure out how to generate the key hierarchy. As this is not standardized, nothing we can assume here. If the provider generates a key hierarchy that is not multi-DRM-compatible then that's too bad but nothing we can do about it.

From this I infer a principle: it is up to the creator of the key hierarchy to ensure it can be used with all relevant DRM systems. If the DRM system hierarchies are incompatible, using both DRM systems together in a CPIX document makes no sense regardless, so we eliminate some potential complexity from the design with this.

I do not believe this changes the basic nature of my proposal above - rather we just get a set of constraints and additional explanation to add here. I will update the above proposal in the near future to integrate the thoughts expressed in this comment.

**Comment by sandersaares** [comment]
A review in yesterday's CPS call identified multi-DRM interoperability as a point that needs further elaboration in this proposal.

Let's consider this from the viewpoint of existing DRM systems that support hierarchical keys (PlayReady and Widevine) and hypothetical future DRM systems that do so.

In the call, the question of key hierarchy creation was raised - do differenr DRM systems do it the same way? This is not at all standardized, so are there compatibility issues?

After checking the two existing implementations of key hierarchies - PlayReady and Widevine - I can say that there are no compatibility issues on the level of key hierarchy creation. The root keys and leaf keys can be generated "naturally" without any specific restrictions in both cases and I expect the same to hold true for any hypothetical future DRM systems.

I note that PlayReady does provide fine-grained control of key management using some specialized algorithms but this is exposed only on the DRM layer and does not surface in CPIX itself. For example, with PlayReady you can make a rule saying "this leaf key is only accessible for subscribers of the premium package". This information only affects the contents of the DRM system specific signaling data and the licenses returned from the license server - the keys are not affected by any of this.

I will amend my proposal above to also reflect this more clearly and to perhaps provide some examples of multi-DRM scenarios.

**Comment by sandersaares** [comment]
I have updated my comment with the proposed edits to CPIX above.

It was requested in the call that a multi-DRM example be provided but after doing the update, I see that a multi-DRM example is no different from a single-DRM example. DRM system specifics do not affect key hierarchies at all (besides just supplying DRMSystem elements to signal multiple DRM systems). The minimum you need for a multi-DRM key hierarchy is just two `ContentKey` elements, one having a `@dependsOnKey` pointing to the other. That's it.

It is possible that the apparent complexity that came up in the CPS call was due to the misconception that root and leaf keys are not treated as independent by all existing implementations. This misconception, which I admit I contributed to, appears to be untrue.

I request further feedback on whether there is anything more to clarify here.

**Comment by lpiron** [comment]
What about adding an attribute @hasKeyhierarchy (Boolean) under the CPIX element. The only way to know otherwise if key hierarchy is present in the CPIX document is looking for contentKey elements with @dependsOnKey attributes

**Comment by sandersaares** [comment]
What scenario do you envision using that attribute in, as a CPIX consumer? All those that I have so far envisioned in my head have been cases where the consumer already knows whether it is expecting hierarchical keys or regular ones (as the business logic related to both is very different, whatever API is processing CPIX has to be designed for one or the other anyway I think).

**Comment by lpiron** [comment]
I'm not sure that the difference in term of API usage will be that different. Adding this top attribute would then be a easy way to know what to expect.

**Comment by sandersaares** [comment]
Let's consider another viewpoint: what would you do based on this information?

The one place that pops into my mind is to distinguish between "CPIX full of root keys" versus "CPIX full of non-hierarchical keys" when handing keys over to a license server. As hierarchical keys need to be associated with each other (they are part of a key sequence) and possibly decorated with DRM specific metadata (policy configuration information), this needs to take place as part of a DRM- and/or vendor-specific API regardless.

Such an API needs to be hierarchy-aware to process any of this implementation-specific information anyway, so taking the knowledge of "this is going to be a CPIX full of root keys" from the API level seems to me quite natural - any attribute in the document talking about hierarchy could just be for logic saying "reject documents that do not have this flag" but that does not seem a useful thing to do (the caller is already signaling a hierarchy by calling the hierarchical keys import API).

Beyond the scenario of passing root keys to a license server, I think none of the use cases we have benefit from such top level metadata. Do you see any other usage for it?

I generally would hesitate to add metadata that affects the interpretation of other parts of the document because it feels to me that it just creates more opportunities for things to break and for parsers to interpret differently by accident. So I would like to be sure it is really justified if such a thing were to be incorporated.

**Comment by sandersaares** [comment]
Notes to self from F2F:

* Format the proposal as CR document for easy review.
* Make it clear that this is an optional feature.
* Examples would be good.

**Comment by sandersaares** [comment]
The above points fulfilled in CPIX 2.1 draft 4.

**Comment by sandersaares** [comment]
I made an error in the following

> When the key is not part of a key hierarchy or is a root key in a key hierarchy, the value is inserted under the moov box.

This is wrong - IOP says that PSSHs should not be inserted under moov boxes at all (instead they should be in the manifest). This might be okay as a "MAY", with perhaps a "SHOULD NOT" as well.

**Comment by lpiron** [comment]
Text integrated in Draft 6.
