### ISSUE TITLE
Support for Microsoft SmoothStreaming

### ISSUE THREAD

**Issue by spuppala** [Dash-Industry-Forum/CPIX#19]
We have been using CPIX payload to transfer key & DRM protection data between encoder and key server.
 
In the DRMSystem element we have PSSH, ContentProtectionData and URIExtXKey which can be used to set DRM protection data for HLS and DASH. We would like to also set Microsoft SmoothStreaming protection header for PlayReady DRM. 
We do see a * element in DRMSystem to support additional media formats, but would like to request the forum if a new element can be added to support PlayReady SmoothStreaming.

**Comment by tinskip** [comment]
What specifically is missing from the spec to support SmoothStreaming?

**Comment by fertunc** [comment]
Hi Thomás, current specification does not have a tag for Rights Management Header. It would be useful to have a dedicated tag to pass Rights Management Header under DRMSystem.

**Comment by sandersaares** [comment]
I recall we are waiting for a proposal on specific wording. If the author of the issue does not wish to make a proposal for the specific wording, here is one I quickly drew up:

---

New `DRMSystem/SmoothStreamingProtectionHeaderData` element added

This is the inner text of the ProtectionHeader XML element to be added to the Smooth Streaming manifest for this DRM system.

This element shall not be used if the referenced Content Key is a leaf key in a key hierarchy.

This element has meaning only when a Smooth Streaming manifest is created for the media content.

---

In CPIX the value of the element is a base64 string that is just copied directly over as a base64 string to the Smooth manifest. Example of how the value would look like in a Smooth Streaming manifest;:

```
<ProtectionHeader SystemID="9a04f079-9840-4286-ab92-e65be0885f95">vAMAAAEAAQCyAzwAVwBSAE0ASABFAEEARABFAFIAIAB4AG0AbABuAHMAPQAiAGgAdAB0AHAAOgAvAC8AcwBjAGgAZQBtAGEAcwAuAG0AaQBjAHIAbwBzAG8AZgB0AC4AYwBvAG0ALwBEAFIATQAvADIAMAAwADcALwAwADMALwBQAGwAYQB5AFIAZQBhAGQAeQBIAGUAYQBkAGUAcgAiACAAdgBlAHIAcwBpAG8AbgA9ACIANAAuADAALgAwAC4AMAAiAD4APABEAEEAVABBAD4APABQAFIATwBUAEUAQwBUAEkATgBGAE8APgA8AEsARQBZAEwARQBOAD4AMQA2ADwALwBLAEUAWQBMAEUATgA+ADwAQQBMAEcASQBEAD4AQQBFAFMAQwBUAFIAPAAvAEEATABHAEkARAA+ADwALwBQAFIATwBUAEUAQwBUAEkATgBGAE8APgA8AEsASQBEAD4AcwByAHUAMQA4AEQASwB2AGoAawB1ADIAMwBvAFQAZABjAHIAcgBZAG0AUQA9AD0APAAvAEsASQBEAD4APABDAEgARQBDAEsAUwBVAE0APgArAHoAVQB5AHoAMQBhAEcAeQBaAE0APQA8AC8AQwBIAEUAQwBLAFMAVQBNAD4APABMAEEAXwBVAFIATAA+AGgAdAB0AHAAcwA6AC8ALwBhAHgAYwBhAHMALgBzAGkAbAB2AGUAcgBoAGQALgBhAHgAdABlAHMAdAAuAG4AZQB0AC8ATABpAGMAZQBuAHMAaQBuAGcAUwB5AHMAdABlAG0ALwBMAGkAYwBlAG4AcwBpAG4AZwBTAGUAcgB2AGkAYwBlAC4AYQBzAG0AeAA8AC8ATABBAF8AVQBSAEwAPgA8AEMAVQBTAFQATwBNAEEAVABUAFIASQBCAFUAVABFAFMAPgA8AFAAcgBvAHQAZQBjAHQAZQBkAFcAaQB0AGgAPgBTAGkAbAB2AGUAcgBIAEQAIABEAFIATQAgADUALgAxAC4AMQA8AC8AUAByAG8AdABlAGMAdABlAGQAVwBpAHQAaAA+ADwASQBJAFMAXwBEAFIATQBfAFYARQBSAFMASQBPAE4APgA3AC4AMQAuADEANQA2ADUALgA0ADwALwBJAEkAUwBfAEQAUgBNAF8AVgBFAFIAUwBJAE8ATgA+ADwALwBDAFUAUwBUAE8ATQBBAFQAVABSAEkAQgBVAFQARQBTAD4APAAvAEQAQQBUAEEAPgA8AC8AVwBSAE0ASABFAEEARABFAFIAPgA=</ProtectionHeader>
```

**Comment by fertunc** [comment]
Thank you for the help Sander. This proposal looks perfect.

**Comment by lpiron** [comment]
Text integrated in Draft 6
