### ISSUE TITLE
Making Data optional in ContentKey

### ISSUE THREAD

**Issue by fertunc** [Dash-Industry-Forum/CPIX#20]
Per CPIX 2.0 specification, minimum occurrence of Data is 1 in ContentKey element under ContentKeyList. In order to make requests more flexible, Data element can be defined as optional in CPIX schema. 

This will make CPIX usage easy in scenarios where requestor just have key-id information but not data/key itself.  DRM client - key server communication is an example where client can request a particular key by passing only kid.

**Comment by lpiron** [comment]
implemented in draft 3
