### ISSUE TITLE
DRMSystem/PSSH specifies invalid PSSH location

### ISSUE THREAD

**Issue by sandersaares** [Dash-Industry-Forum/CPIX#21]
> If a KeyPeriodFilter is defined on the Content Key, then the
> PSSH box goes under the moof box otherwise, the PSSH box
> goes under the moov box.

This is wrong, as DASH-IF IOP says that a (non-hierarchical) key change must start a new period, therefore PSSH **always** goes in moov box in the initialization segment.

However, if we include hierarchical keys (https://github.com/Dash-Industry-Forum/CPIX/issues/17) then the PSSH associated with leaf keys would logically belong in the moof. I will provide the proposed change in the linked issue together with the hierarchical keys proposed text change.

**Comment by lpiron** [comment]
Closed as the resolution came with resolution of bug #17
