### ISSUE TITLE
Guidance on x.509 cert management

### ISSUE THREAD

**Issue by pankaj-giter** [Dash-Industry-Forum/CPIX#24]
For the use of X.509 certificates within the CPIX document, where the certificate enables sharing of ContentKey info with the additional properties of integrity and confidentiality, would we have some best practices to share on managing the life cycle of this certificate? If not, could we provide some?
 
The way I understand it today is that the certificate exchange has to happen through offline channels first, i.e. trust establishment, which invariably becomes a manual process and hence, painful.
Also, aspects to handle expiration of said certificates and revocation is left up to the implementers.

Incidentally, the world of HTTPS has already encountered and solved these problems.
Additionally, the problem of automated bi-directional trust establishment and revocation is similar to mutual-auth in HTTPS. Could we leverage some of the learnings from here?

**Comment by sandersaares** [comment]
Feels like there would be merit in working on this topic further. Let's try.

**Comment by lpiron** [comment]
Closed following Dec 13 call discussion. Closed with no action.
