### ISSUE TITLE
Relax the effect of unknown usage rule filters

### ISSUE THREAD

**Issue by sandersaares** [Dash-Industry-Forum/CPIX#25]
CPIX 2.0 says:

> A usage rule shall be considered invalid if it contains a child element whose meaning is unknown (i.e. a filter of an unknown type) or which cannot be processed for any other reason (e.g. VideoFilter@minPixels is defined but the implementation does not know the pixel count of the video samples). This condition must be treated as a fatal error in the processing of the CPIX document.

This is overly harsh - it should not be considered a fatal error just for processing the document. The only thing that un-processable rules should prevent is the processing of rules to resolve Content Keys. As long as the recipient does not want to resolve Content Keys, it should not break CPIX document processing.

Proposed new wording:

> A usage rule shall be considered unusable if it contains a child element whose meaning is unknown (i.e. a filter of an unknown type) or which cannot be processed for any other reason (e.g. VideoFilter@minPixels is defined but the implementation does not know the pixel count of the video samples). A CPIX processing system must not perform Content Key mapping to Content Key Contexts if any unusable usage rules exist.

**Comment by lpiron** [comment]
Text implemented in draft 8 with a clarification
