### ISSUE TITLE
Define encoding to use for ContentProtectionData and HLSSignalingData

### ISSUE THREAD

**Issue by sandersaares** [Dash-Industry-Forum/CPIX#26]
These are base64binary fields that actually represent text (MPD/M3U8 fragments, respectively). When transforming between text and binary, an encoding must be specified to ensure a common interpretation.

I propose that we define these fields as containing UTF-8 text without a byte order mark.

**Comment by lpiron** [comment]
Description of these elements include this encoding definition (draft 6)
