### ISSUE TITLE
Define ContentProtectionData as well-formed standalone XML fragment

### ISSUE THREAD

**Issue by sandersaares** [Dash-Industry-Forum/CPIX#27]
ContentProtectionData is a fragment of an MPD, intended to be merged into a DASH manifest that makes use of this signaling data. For example, a common element expected to be present in this field is `<cenc:pssh>`.

For the value to be a well-formed XML fragment, the author must declare all namespaces that are used within and cannot assume that readers have some implicit understanding that applies herein.

For proper processing, a reader cannot make assumptions about the structure of the XML data (such as assuming "cenc" or "mpd" namespace prefixes are used).

`<aaaaaaaaaaaaaaaaaaa:pssh xmlns:aaaaaaaaaaaaaaaaaaa="urn:mpeg:cenc:2013"></aaaaaaaaaaaaaaaaaaa:pssh>` is a perfectly valid way to provide a `cenc:pssh` element, for example, and readers must support this.

I propose such a note be added to the definition of this element.

**Comment by lpiron** [comment]
This is added in the description of the element "This is the full well-formed standalone XML element to ..."

**Comment by zoomout** [comment]
Is the ContentProtectionData's value a base64 encoded content of ContentProtection or a base64 encoded ContentProtection element itself?
Given two example below, which one should be base64 encoded and put as a value of ContentProtectionData?
1. 
`<cenc:pssh> urn:mpeg:cenc:2013">BASE64_PSSH</cenc:pssh>`
2. 
```
<ContentProtection schemeIdUri="urn:uuid:9A04F079-9840-4286-AB92-E65BE0885F95">
    <cenc:pssh> urn:mpeg:cenc:2013">BASE64_PSSH</cenc:pssh>
</ContentProtection>
```

**Comment by sandersaares** [comment]
The documen text says "under the ContentProtection element" which I interpret as meaning "as child":

> This is the full well-formed standalone XML fragment to be added to the DASH manifest under the ContentProtection element for this DRM system.

So option 1 from your list. Please note that this XML fragment must be well-formed (your example does not declare the cenc namespace, which is required for it to be valid XML).

We also have some test data at https://github.com/Dash-Industry-Forum/cpix-test-vectors among which I believe the one named `Complex` contains ContentProtectionData elements.
