### ISSUE TITLE
Clarify how UpdateHistoryItem is supposed to be referenced

### ISSUE THREAD

**Issue by sandersaares** [Dash-Industry-Forum/CPIX#28]
Various things have a `@updateVersion` attribute of type `integer`. Description says this references `UpdateHistoryItem@id`, which is `xs:ID` and allows for a wider range of values. This is a conflict.

There is also `UpdateHistoryItem@index` that seems a potential match for `@updateVersion` (though why is it not `UpdateHistoryItem@version` then?).

Is there an error somewhere? Should `@updateVersion` instead reference `@index`?

**Comment by lpiron** [comment]
corrected in the version under review
