### ISSUE TITLE
Microsoft SmoothStreaming protection header value

### ISSUE THREAD

**Issue by spuppala-verimatrix** [Dash-Industry-Forum/CPIX#29]
The description of the SmoothStreamingProtectionHeaderData element added in the latest version of CPIX(v2.1) is 

> This is the inner text of the ProtectionHeader XML element to be added to the Smooth Streaming manifest for this DRM system. This is a UTF-8 text without a byte order mark.
This element shall not be used if the referenced Content Key is a leaf key in a key hierarchy.
This element has meaning only when a Smooth Streaming manifest is created for the media content.

However this format of the header does not align with the PlayReady specification as described here - http://download.microsoft.com/download/2/3/8/238F67D9-1B8B-48D3-AB83-9C00112268B2/PlayReady Header Object 2015-08-13-FINAL-CL.PDF

The header value should be UTF-16 encoded XML with LittleEndian byte order.

In a previous issue [#19](19) regarding the addition of the element, the description proposed was different from the one in the latest draft. It would be great if the wording can be changed back to the proposed description.

**Comment by lpiron** [comment]
The format was added to ensure we have one defined. As Microsoft has already defined its own format, it will be aligned. I will correct it.

**Comment by sandersaares** [comment]
There are different layers here that likely cause some confusion.

The Microsoft spec is about the textual content inside the base64 bytestring.

The original text in the linked CPIX issue that I proposed was intended to express that CPIX simply carries the base64 bytestring as text, to be directly inserted as the inner text of the XML element in the CPIX document. This avoids any encoding questions as we can thereby work directly with text and never convert between bytes and text. Perhaps the wording was insufficiently clear on that, though.

That is to say, if the element in CPIX has a base64 bytestring saying "TWFuIGlzIGRpc3Rpbmd1aXNoZWQsIG5vdCBvbmx5IGJ5IGhpcyByZWFzb24sIGJ1dCBieSB0aGlz" it would always be in the Smooth Streaming manifest as "TWFuIGlzIGRpc3Rpbmd1aXNoZWQsIG5vdCBvbmx5IGJ5IGhpcyByZWFzb24sIGJ1dCBieSB0aGlz". If we introduce any question of encoding, new layers appear in the workflow (which we can just avoid).

**Comment by spuppala-verimatrix** [comment]
Thanks @lpiron. I agree with @sandersaares. The value expected would be something like 
`<SmoothStreamingProtectionHeaderData>AgMAAAEAAQD4AjwAVwBSAE0ASABFAEEARABFAFIAIAB4AG0AbABuAHMAPQAiAGgAdAB0AHAAOgAvAC8AcwBjAGgAZQBtAGEAcwAuAG0AaQBjAHIAbwBzAG8AZgB0AC4AYwBvAG0ALwBEAFIATQAvADIAMAAwADcALwAwADMALwBQAGwAYQB5AFIAZQBhAGQAeQBIAGUAYQBkAGUAcgAiACAAdgBlAHIAcwBpAG8AbgA9ACIANAAuADAALgAwAC4AMAAiAD4APABEAEEAVABBAD4APABQAFIATwBUAEUAQwBUAEkATgBGAE8APgA8AEsARQBZAEwARQBOAD4AMQA2ADwALwBLAEUAWQBMAEUATgA+ADwAQQBMAEcASQBEAD4AQQBFAFMAQwBUAFIAPAAvAEEATABHAEkARAA+ADwALwBQAFIATwBUAEUAQwBUAEkATgBGAE8APgA8AEsASQBEAD4AQwB0AG4AMwBWAEMAKwA4AG0ANwB3AEkAMQBMAHYAcQB4AE0AegB3AGkAdwA9AD0APAAvAEsASQBEAD4APABDAEgARQBDAEsAUwBVAE0APgBCAGkAOABtAFYATgA3ADYATQBRAGMAPQA8AC8AQwBIAEUAQwBLAFMAVQBNAD4APABMAEEAXwBVAFIATAA+AGgAdAB0AHAAOgAvAC8AMQAyADcALgAwAC4AMAAuADEALwBQAGwAYQB5AFIAZQBhAGQAeQAvAHIAaQBnAGgAdABzAG0AYQBuAGEAZwBlAHIALgBhAHMAbQB4ADwALwBMAEEAXwBVAFIATAA+ADwATABVAEkAXwBVAFIATAA+AGgAdAB0AHAAOgAvAC8AMQAyADcALgAwAC4AMAAuADEALwBQAGwAYQB5AFIAZQBhAGQAeQAvAHIAaQBnAGgAdABzAG0AYQBuAGEAZwBlAHIALgBhAHMAbQB4ADwALwBMAFUASQBfAFUAUgBMAD4APAAvAEQAQQBUAEEAPgA8AC8AVwBSAE0ASABFAEEARABFAFIAPgA=</SmoothStreamingProtectionHeaderData>`

**Comment by lpiron** [comment]
OK, no changes or a clarification ? Does not seem really clear in the description of the element in the CPIX spec.

**Comment by sandersaares** [comment]
This makes me realize that what we lack in CPIX is a clear definition of data types. We name the elements but do not say what they are.

This SmoothStreamingProtectionHeaderData should be a string. This might more explicitly signal that it is text to be taken from one XML document and directly inserted to another.

In contrast, its neighbors are base64string because they are binary data (just that binary data happens to be text in CPIX-defined encoding, containing some XML).

We can get away without this encoding layer because the MSS data is not XML but just plain text (which just happens to always contain a base64 string but that is MSS-specific detail that we can ignore in CPIX).

Besides specifying the data type, I do not have good ideas how to make it more clear than in the proposed text in #19. Perhaps just ensuring that we make some good examples for this point might be best? Example CPIX + example resulting MSS?

**Comment by lpiron** [comment]
Th type of elements and attributes are given in the XSD. We could add a column to all tables giving the type but reading may become difficult. 
Having examples sounds like a good idea

**Comment by sandersaares** [comment]
In the Bikeshed authoring experiment, I tried placing the data type next to the expected values count to make it more visible. Maybe this style might make it more clear? See http://media.axprod.net/temp/cpix-authoring-experiment/#schema-deliverydata

**Comment by lpiron** [comment]
Drawing are updated with the types (applied in both Words and Bikeshed) and the Bikeshed version also includes types as part of the definition of elements

**Comment by sandersaares** [comment]
Oh, I notice in the document for Community Review this is still `xs:base64string`. In my proposal for the text I intended it to be `xs:string` (to match the description).

**Comment by lpiron** [comment]
Need to correct both the Words and XSD

**Comment by lpiron** [comment]
Corrected and new versions created
