### ISSUE TITLE
ContentProtectionData description does not match with examples

### ISSUE THREAD

**Issue by sgrelet** [Dash-Industry-Forum/CPIX#31]
For `ContentProtectionData`, the 2.1 draft specification says:

> This is the full well-formed standalone XML element to be added to the DASH manifest under the ContentProtection element for this DRM system. 

The word "**under**" means that it should not contain `<ContentProtection>` tags.
Two issues:
- The official examples are not consistent as they include  `<ContentProtection>` tags.
- In some cases, `<ContentProtection>` tags are useful to let the DRM server include namespaces that the packager may not know.

**Comment by sgrelet** [comment]
With issue #32, you confirm that the `ContentProtectionData` must not contain the `<ContentProtection>` tags, right?

**Comment by sandersaares** [comment]
The description is indeed open to interpretation - we will review this topic in the next security task force call and attempt to form a common understanding.

My personal view is that this should say "inner XML of the ContentProtection element" (but yes, not including the ContentProtection element itself). However, this needs to be aligned with the rest of the group.

**Comment by lpiron** [comment]
This is indeed what was expected there. The DRM server is providing only the inner part of the <contentProtection> element. The reason for not having the DRM server providing the tag is that there may be cases where more that one DRM server provide information going in the inner part of the contentProtection element.
Which examples are not consistent ?

**Comment by sgrelet** [comment]
I did not realize there could be use cases with several `ContentProtectionData` elements for a same DRM going into a single `<ContentProtection>`.

But my second question is still valid: How do we inform the packager about the possible namespaces needed for defining the elements in `<ContentProtection>`? Should we introduce in a next CPIX version a new element in `ContentProtectionData` describing the namespaces?

About one example which is not consistent, there is clearKey.xml delivered with final CPIX 2.0.

**Comment by sandersaares** [comment]
The namespaces can simply be declared in the content of the element. Example:

```
<ContentProtectionData>
PHBzc2ggeG1sbnM6Y2VuYz0idXJuOm1wZWc6Y2VuYzoyMDEzIj5BQUFCNUhCemMyZ0FBQUFBbWdUd2VaaEFRb2Fya3VaYjRJaGZsUUFBQWNURUFRQUFBUUFCQUxvQlBBQlhBRklBVFFCSUFFVUFRUUJFQUVVQVVnQWdBSGdBYlFCc0FHNEFjd0E5QUNJQWFBQjBBSFFBY0FBNkFDOEFMd0J6QUdNQWFBQmxBRzBBWVFCekFDNEFiUUJwQUdNQWNnQnZBSE1BYndCbUFIUUFMZ0JqQUc4QWJRQXZBRVFBVWdCTkFDOEFNZ0F3QURBQU53QXZBREFBTXdBdkFGQUFiQUJoQUhrQVVnQmxBR0VBWkFCNUFFZ0FaUUJoQUdRQVpRQnlBQ0lBSUFCMkFHVUFjZ0J6QUdrQWJ3QnVBRDBBSWdBMEFDNEFNQUF1QURBQUxnQXdBQ0lBUGdBOEFFUUFRUUJVQUVFQVBnQThBRkFBVWdCUEFGUUFSUUJEQUZRQVNRQk9BRVlBVHdBK0FEd0FTd0JGQUZrQVRBQkZBRTRBUGdBeEFEWUFQQUF2QUVzQVJRQlpBRXdBUlFCT0FENEFQQUJCQUV3QVJ3QkpBRVFBUGdCQkFFVUFVd0JEQUZRQVVnQThBQzhBUVFCTUFFY0FTUUJFQUQ0QVBBQXZBRkFBVWdCUEFGUUFSUUJEQUZRQVNRQk9BRVlBVHdBK0FEd0FTd0JKQUVRQVBnQndBRFVBWkFCSUFGY0FVUUJDQUhJQVl3QXdBR0VBZVFBMEFHRUFOd0E0QUZZQVV3QnpBR0lBZGdCQkFEMEFQUUE4QUM4QVN3QkpBRVFBUGdBOEFDOEFSQUJCQUZRQVFRQStBRHdBTHdCWEFGSUFUUUJJQUVVQVFRQkVBRVVBVWdBK0FBPT08L3Bzc2g+DQo8cHJvIHhtbG5zPSJ1cm46bWljcm9zb2Z0OnBsYXlyZWFkeSI+eEFFQUFBRUFBUUM2QVR3QVZ3QlNBRTBBU0FCRkFFRUFSQUJGQUZJQUlBQjRBRzBBYkFCdUFITUFQUUFpQUdnQWRBQjBBSEFBT2dBdkFDOEFjd0JqQUdnQVpRQnRBR0VBY3dBdUFHMEFhUUJqQUhJQWJ3QnpBRzhBWmdCMEFDNEFZd0J2QUcwQUx3QkVBRklBVFFBdkFESUFNQUF3QURjQUx3QXdBRE1BTHdCUUFHd0FZUUI1QUZJQVpRQmhBR1FBZVFCSUFHVUFZUUJrQUdVQWNnQWlBQ0FBZGdCbEFISUFjd0JwQUc4QWJnQTlBQ0lBTkFBdUFEQUFMZ0F3QUM0QU1BQWlBRDRBUEFCRUFFRUFWQUJCQUQ0QVBBQlFBRklBVHdCVUFFVUFRd0JVQUVrQVRnQkdBRThBUGdBOEFFc0FSUUJaQUV3QVJRQk9BRDRBTVFBMkFEd0FMd0JMQUVVQVdRQk1BRVVBVGdBK0FEd0FRUUJNQUVjQVNRQkVBRDRBUVFCRkFGTUFRd0JVQUZJQVBBQXZBRUVBVEFCSEFFa0FSQUErQUR3QUx3QlFBRklBVHdCVUFFVUFRd0JVQUVrQVRnQkdBRThBUGdBOEFFc0FTUUJFQUQ0QWNBQTFBR1FBU0FCWEFGRUFRZ0J5QUdNQU1BQmhBSGtBTkFCaEFEY0FPQUJXQUZNQWN3QmlBSFlBUVFBOUFEMEFQQUF2QUVzQVNRQkVBRDRBUEFBdkFFUUFRUUJVQUVFQVBnQThBQzhBVndCU0FFMEFTQUJGQUVFQVJBQkZBRklBUGdBPTwvcHJvPg0K
</ContentProtectionData>
```

After decoding:

```
<pssh xmlns:cenc="urn:mpeg:cenc:2013">AAAB5HBzc2gAAAAAmgTweZhAQoarkuZb4IhflQAAAcTEAQAAAQABALoBPABXAFIATQBIAEUAQQBEAEUAUgAgAHgAbQBsAG4AcwA9ACIAaAB0AHQAcAA6AC8ALwBzAGMAaABlAG0AYQBzAC4AbQBpAGMAcgBvAHMAbwBmAHQALgBjAG8AbQAvAEQAUgBNAC8AMgAwADAANwAvADAAMwAvAFAAbABhAHkAUgBlAGEAZAB5AEgAZQBhAGQAZQByACIAIAB2AGUAcgBzAGkAbwBuAD0AIgA0AC4AMAAuADAALgAwACIAPgA8AEQAQQBUAEEAPgA8AFAAUgBPAFQARQBDAFQASQBOAEYATwA+ADwASwBFAFkATABFAE4APgAxADYAPAAvAEsARQBZAEwARQBOAD4APABBAEwARwBJAEQAPgBBAEUAUwBDAFQAUgA8AC8AQQBMAEcASQBEAD4APAAvAFAAUgBPAFQARQBDAFQASQBOAEYATwA+ADwASwBJAEQAPgBwADUAZABIAFcAUQBCAHIAYwAwAGEAeQA0AGEANwA4AFYAUwBzAGIAdgBBAD0APQA8AC8ASwBJAEQAPgA8AC8ARABBAFQAQQA+ADwALwBXAFIATQBIAEUAQQBEAEUAUgA+AA==</pssh>
<pro xmlns="urn:microsoft:playready">xAEAAAEAAQC6ATwAVwBSAE0ASABFAEEARABFAFIAIAB4AG0AbABuAHMAPQAiAGgAdAB0AHAAOgAvAC8AcwBjAGgAZQBtAGEAcwAuAG0AaQBjAHIAbwBzAG8AZgB0AC4AYwBvAG0ALwBEAFIATQAvADIAMAAwADcALwAwADMALwBQAGwAYQB5AFIAZQBhAGQAeQBIAGUAYQBkAGUAcgAiACAAdgBlAHIAcwBpAG8AbgA9ACIANAAuADAALgAwAC4AMAAiAD4APABEAEEAVABBAD4APABQAFIATwBUAEUAQwBUAEkATgBGAE8APgA8AEsARQBZAEwARQBOAD4AMQA2ADwALwBLAEUAWQBMAEUATgA+ADwAQQBMAEcASQBEAD4AQQBFAFMAQwBUAFIAPAAvAEEATABHAEkARAA+ADwALwBQAFIATwBUAEUAQwBUAEkATgBGAE8APgA8AEsASQBEAD4AcAA1AGQASABXAFEAQgByAGMAMABhAHkANABhADcAOABWAFMAcwBiAHYAQQA9AD0APAAvAEsASQBEAD4APAAvAEQAQQBUAEEAPgA8AC8AVwBSAE0ASABFAEEARABFAFIAPgA=</pro>
```

**Comment by sandersaares** [comment]
My example also contradicts the spec a bit, as I specify two elements (spec says "XML element", singular). I would probably see "inner XML" as the most appropriate term instead of "XML element".

**Comment by sandersaares** [comment]
DASH 5.8.2 defines the basic features of the ContentProtection element. Among these is that the owner of the scheme (i.e. the DRM system in this case) defines the meaning of the `@value` attribute. This is not expressed in CPIX if we only include the content of this element in CPIX.

On the other hand, I believe no DRM system actually uses `@value` so this may be rather irrelevant in practice.

**Comment by sgrelet** [comment]
As #32 as been created and my namespace concern is answered, I think I can close this ticket.
