### ISSUE TITLE
Make better samples

### ISSUE THREAD

**Issue by sandersaares** [Dash-Industry-Forum/CPIX#32]
The samples we published with 2.0 have some issues:

* They deviate from the spec in some ways (#31).
* They are full of dummy (even invalid) data that does not match real world use cases.
* There are very few of them.
* Some samples referenced by the spec are actually missing (hierarchical keys).

We should improve the set of samples in all these regards, publishing a nice and meaningful set.

**Comment by lpiron** [comment]
Added in Release 2.1
