### ISSUE TITLE
Purpose of index attribute in ContentKeyPeriod is not specified

### ISSUE THREAD

**Issue by wilevers** [Dash-Industry-Forum/CPIX#33]
According to the CPIX spec, a **ContentKeyPeriod** element may carry the **start** and **end** attributes, which together define the key period interval, or it carries the **index** attribute, which is mutually exclusive with **start** and **end**. It is not specified how the key period interval should be determined when the **index** attribute is set and we therefore do not have a **start** and **end**.

**Comment by sandersaares** [comment]
I believe the idea is that `ContentKeyPeriod@index` can be used if the mapping to timestamps is to be decided by the consuming component and the producer of the ContentKeyPeriod element does not know nor need to know it - for scenarios where only the order is relevant.

@tinskip any comments? Do I remember it right? I vaguely recall that this element originated with you - correct me if I am wrong.

**Comment by lpiron** [comment]
Yes, this is the idea. This is following the "classical" payTV scenario where broadcast content has the index or Id of the key to use for been decrypted. Keys are delivered  with the matching index. The advantage of this mechanism is that, if for any reason, the encryption tool can not get a new key it keeps using the existing one. Content remains encrypted. The description should go in a more generic document about encryption of Live content with key rotation.

**Comment by wilevers** [comment]
I'm still unsure how to evaluate a KeyPeriodFilter if it refers to a ContentKeyPeriod that just carries the **index** attribute without a [**start**,**end**> range. It seems to me the CPIX document alone does not provide enough information to decide which content key to apply for a given point in the timeline. 

Any hints? Thanks!

**Comment by sandersaares** [comment]
> It seems to me the CPIX document alone does not provide enough information to decide which content key to apply for a given point in the timeline.

Yes. The decision to when to switch to the next key in this scenario will need to be taken by the thing consuming the keys/periods.

**Comment by wilevers** [comment]
OK; thanks for the clarification. It would say this deserves some explanatory note in the CPIX spec.

**Comment by lpiron** [comment]
Merged proposed changes
