### ISSUE TITLE
dependsOnKey should be defined as optional

### ISSUE THREAD

**Issue by sgrelet** [Dash-Industry-Forum/CPIX#34]
In section _[ContentKey element](http://dashif.org/wp-content/uploads/2018/03/Cpix/Index.html#schema-contentkey)_, `dependsOnKey` is defined as mandatory but, according to the definition, it is actually not.

**Comment by sandersaares** [comment]
Good catch! You are entirely correct.

**Comment by lpiron** [comment]
Corrected with pull request [https://github.com/Dash-Industry-Forum/CPIX/pull/35](url). Note that the document under review (PDF version at dashif.org) is not corrected, only the Bikeshed version under Github.
