### ISSUE TITLE
Add missing systemIds

### ISSUE THREAD

**Issue by unifiedstreaming** [Dash-Industry-Forum/CPIX#37]
In http://dashif.org/identifiers/protection a list of systemIds is presented, however, there is no systemID for the following:

HDS
- has not systemId, should Adobe's be used (the one from DASH)?

HLS
- AES-128: missing
- ChinaDRM: missing
- Conax: missing
- Irdeto PR: missing
- Irdeto PRSL: missing
- Playready Envelope: missing
- Primetime: missing
- SAMPLE-AES: missing
- Viacces/Orca PR: missing

In SPEKE (based on CPIX) a systemId for for instance AES-128 can be found (https://docs.aws.amazon.com/speke/latest/documentation/vod-workflow-methods.html), is this from a list part of CPIX?

Could above systemIds be added or could there be some guidance on what to use according to CPIX?

**Comment by unifiedstreaming** [comment]
Added request: https://github.com/Dash-Industry-Forum/CPIX/issues/37

**Comment by sandersaares** [comment]
DASH-IF publishes system IDs upon submission by the owner of the DRM system in question.

The optimal way to get any missing system IDs published would be to ask the owners of these DRM systems to submit them to DASH-IF for registration. I am currently unable to find any detailed process documented for this but an email to dashindustry@live.com would likely be a good starting point.

**Comment by unifiedstreaming** [comment]
Are the systemIds then not limited to DASH?

**Comment by sandersaares** [comment]
The system IDs are generic concept. DASH-IF just happened to be the first one doing a centralized publishing of them and is de-facto the registry, though they are also used outside DASH context.

**Comment by lpiron** [comment]
Can you clarify what "DRM systems" you mean under "AES-128" and "SAMPLE-AES" ? From RFC 8216, these are identifiers of content encryption methods, not identifiers of DRM system identifiers.
In the list you provide, ChinaDRM is a special case as this is a standardisation body, we took an action to check with them if they can/want to register something.

**Comment by unifiedstreaming** [comment]
Hi, That is indeed what the difficulty is: AES-128 and SAMPLE-AES is not a 'DRM System' but encryption, for which keys can be self hosted. The SPEKE example says for instance ''

Perhaps there could be a systemId for both indicating 'self-hosted key'? Specific implementations could override, but at least there would be a default.

**Comment by lpiron** [comment]
In the example given by AWS, only AES-128 is implementation specific. For SAMPLE-AES, the systemID refers to FairPlay. I assume, the "key management" under the AES-128 systemID is the one described by the HLS spec under section 5. I'm not sure who should register such ID. Apple ?

**Comment by unifiedstreaming** [comment]
Thanks! Regarding the systemId when there is no vendor involved, it's a local self hosted setup or testing, would it make sense to recommend '00000000-0000-0000-0000-000000000000' ?

**Comment by lpiron** [comment]
We discussed this in the call yesterday and a proposal would be to register a range of IDs 00000000-0000-0000-0000-000000000000 to 00000000-0000-0000-0000-000000000099 and to reserve them for "private use" as it is commonly done (for local self hosted setup or testing). 
That would ensure at 100% that there will be no collusion and a range offer more flexibility.

Comments?

**Comment by sandersaares** [comment]
I would pick a random range that is not zeroes (e.g. 33580f5a-6bb1-40cd-8c12-b1d4ef2c0000 to 33580f5a-6bb1-40cd-8c12-b1d4ef2c00ff), to avoid conflicts with other types of "zero values".

Note that a GUID with all zeroes is also nonconforming to the UUID v4 specification, which is the one most often followed - some of the conents are actually signaling bits for the UUID version number.
