### ISSUE TITLE
The way to make a period of time in the clear is not explicit

### ISSUE THREAD

**Issue by TanguyPerson** [Dash-Industry-Forum/CPIX#38]
The requirements (§4.5) include the fact to make some period of time in the clear:

> Update of Content Key(s) shall be possible at periodic time or based on events.
> Some period of time could be in the clear (no encryption).

It is unclear to me how to generate and interpret CPIX documents for such case.

As far as I understand:
- ContentKeyPeriod elements should define time ranges.
- ContentKeyUsageRule elements should then associate content keys (kid, mandatory attribute) with scrambled time ranges (with KeyPeriodFilter elements).

As ContentKeyUsageRule@kid is mandatory, it doesn't seem possible to explicitly state that a period is intended to be in the clear. 

Note that there could other use cases, e.g. to make audio of low video bitrates explicitly not scrambled.

Making things explicit in CPIX documents avoids surprises and mis-interpretations. For example, if a packager doesn't find any ContentKeyUsageRule element matching a HEVC UHD track, how to guess if the content publisher _intend_ was to to really stream UHD track in the clear, or was it a error in CPIX documentation generation ?

So, how to make in-the-clear time periods or media components would be worth be explicit-ed in the specification.

**Comment by tinskip** [comment]
I think this is two issues: 

(1) Allowing clear periods. Is this in the scope of CPIX? Is "no protection" a type of protection? Is it sufficient to assume that any undefined periods are clear? Or do we need a "default" state which specifies a fallback key id or no key (clear)? Or should we require that every period be defined?

(2) Specifying unprotected streams.  Again is this within the scope of CPIX?  Can we assume that any non-matching streams are clear (dangerous)?  A default action?  Require that every stream be matched?

**Comment by lpiron** [comment]
The document is articulated around content keys. Other main elements are referencing content keys they apply to (this is why kid is mandatory) . If there is no encryption, then there are no content keys and creating a CPIX document does not really make sense.
I agree with @tinskip that in the clear content is not in the scope as there are no content keys in this case.
Regarding the unprotected streams, we cannot require anything, I'm pretty sure someone can find a case where it make sense and a case where it does not make sense. This should be left to deployment options.

**Comment by lpiron** [comment]
If there is no additional comment before tomorrow, I propose to close this bug with "no action".

**Comment by TanguyPerson** [comment]
@tinskip @lpiron Clear periods of content are explicitly in the scope, as it is listed in the requirements in §4.5
> Some period of time could be in the clear (no encryption).
But so far the specification gives to clue on how to implement that.

@tinskip proposal meets my request by allow explicit non-encryption policy, but obviously there is no consensus so far.

The question of "fully clear content" is a separate one and is not explicitly in the scope.

An alternate action would be
- to remove the "clear periods" from the scope by modifying § 4.5
- and to explicitly state that behaviour in such case is out of the specification and deployment-defined, as proposed by @lpiron 

Though it doesn't meet my expectation, it would explicit the bounds of the specification.

**Comment by lpiron** [comment]
Clear period mean that there is no content key, hence creating dummy ones looks a bit awkward as the only goal then is to use CPIX for storing the encrypted/clear status. This information is already available in other part of the system and the logic of encrypting or not is on the scrambler side.
When comparing to Simulcrypt, the SCS is asking ECM to the ECMG only when it makes sense and the mux creates then the right signaling allowing the STB to act correctly (setting the scramble bits). The CAS has not necessarily the knowledge that content is sometimes in the clear.
It is possible to support clear periods with CPIX. There will simply be no associated document for this period. The information that content is encrypted or not would be known by either looking at the playlist/manifest or any other specific deployment source of data (such as EPG, a metadata server).

**Comment by TanguyPerson** [comment]
So CPIX should focus on **how**  content should be protected (which key for which media component or time range, which DRM signalling), and not about **whether**, **when** and **on what** protection should be applied.

It makes senses, but in such case, it should be explained better in the document, for example:

> The following is out of specification and should be defined by application:
> - whether protection defined the CPIX document should be applied or not
> - behaviour to be used for media components not covered by filter rules
> - behaviour to be used for time periods not covered in CPIX document

**Comment by lpiron** [comment]
I agree that some additional text is needed. Thanks for the proposal, I'll create a pull request and try to clarify.

**Comment by TanguyPerson** [comment]
It is clearer now.
