### ISSUE TITLE
Distinction between HLSSignalingData for Master playlists and Media playlists

### ISSUE THREAD

**Issue by unifiedstreaming** [Dash-Industry-Forum/CPIX#42]
For different DRM systems such as Irdeto Playready for HLS, Discretix, Adobe Primetime, there are different signaling tags in the Master Playlist .m3u8 compared to the Media Playlist .m3u8.

For example with Irdeto Playready for HLS, in the Master playlist a #X-IRDETO-PROTECT-HEADER tag is found, and in the Media playlist a #X-IRDETO-PROTECT and #X-IRDETO-KEY in place of #EXT-X-KEY.

There needs to be a way to store this signaling.

**Comment by lpiron** [comment]
HLS specification has two flags EXT-X-KEY and EXT-X-SESSION-KEY.
CPIX currently only describes what to add under EXT-X-KEY. We should then either extend the description of the HLSSignalingData for including the  EXT-X-SESSION-KEY signaling or create a new element for this signaling.

**Comment by sanao** [comment]
From my understanding, EXT-X-SESSION-KEY have the same value like EXT-X-KEY. So, we don't need to add new element for this signaling.

The RFC part about the EXT-X-SESSION-KEY tag => https://tools.ietf.org/html/rfc8216#page-35

**Comment by lpiron** [comment]
Agree, but it seems some companies are adding extra proprietary tags and these are different if after EXT-X-KEY or after EXT-X-SESSION-KEY.

**Comment by unifiedstreaming** [comment]
From the CPIX spec v2.1 on the HLSSignalingdata:

This is the full data including the #EXT-X-KEY tag of a HLS playlist. This may contain multiple lines allowing to add lines with proprietary tags and values.

It seems the proprietary tags have been taken into account. It looks like a similar element for the #EXT-X-SESSION-KEY with the same definition would work well.

**Comment by lpiron** [comment]
A proposal from @tinskip is to make HLSSignalingData 0..2 instead of 0..1 and to add an optional String attribute (name to be defined) with EXT-X-KEY and EXT-X-SESSION-KEY as possible values. You could then defined the data to be added under each tag. This is backward compatible if you only have one element and do not provide the String attribute.

**Comment by lpiron** [comment]
If there is no additional comment by tomorrow, I will update the specification and XSD accordingly.

**Comment by lpiron** [comment]
Changes committed
