### ISSUE TITLE
CPIX 2.1 Key Rotation  - Interoperability 

### ISSUE THREAD

**Issue by karlg-arris** [Dash-Industry-Forum/CPIX#44]
Hi,

I have a number of queries/concerns regarding CPIX 2.1 regarding the signalling of key rotation and interoperability between DRM systems that may take different approaches in implementing this feature.

1.)There does not seem to be a method for signalling a 'leaf' key dependancy (on a root key) that is applicable to only a single DRM (or a subset of support DRM systems).  This could cause incorrect signalling being added by the packager/encryptor for DRMs that don't support key hierarchy - which might then lead clients to attempt playback without a valid content encryption key acquired or impede the detection of key rotation boundaries.

2.)The definition for DRMSystem:PSSH states that the element should not be used if the key is not part of a hierarchy. However, for some DRM systems the key may not be part of a hierarchy but it may be still part of a 'rotated set'  - thus related PSSH data needs to be inserted into the content (moof) so that the DRM client can invoke the necessary license acquisition(s).  Please note that the DASH-IOP does not seem to preclude the insertion of  PSSH data in a moof fragment that may only contain signalling information (not a leaf key)

**Comment by karlg-arris** [comment]
I think the point raised in 1.) could also effect HLS too.  The description of HLSSignalling data means that it should not be included if the key is dependant on a root key.

This would break FairPlay in the instance that the ContentKey was shared between DASH and HLS

**Comment by lpiron** [comment]
if key hierarchy is used then all DRM that are enabled for this piece of content shall support key hierarchy. One important goal of key hierarchy is to enable frequent changes of content key while minimizing the impact on the license server. It is true that as of today, only a subset of DRMs support key hierarchy, hence if there is a mix of DRM, then key rotation should be deployed without key hierarchy. The DRM that does not support it will most probably not allow proper rendering as it will constantly request licenses based on new keyIDs.

**Comment by sandersaares** [comment]
I would additionally emphasize that CPIX is designed to cover *interoperable* key scenarios. If one DRM system requires special key management that is not compatible with the individual or hierarchical key structures enabled by CPIX, that DRM system is not compatible with CPIX.

The lack of any way to specify DRM system specific key handling is very much intentional.

**Comment by karlg-arris** [comment]
@sandersaares @lpiron 

Let me provide some clarifications.

I am not necessarily referring to 'special'  key management.  It is more about being able to leverage the extra scalability of a key hierarchy as and when supported without requiring all DRMs to support it.

@lpiron as you have said the intent seems to be that all DRM systems would have to support key hierarchy if you want to signal that approach.  However we know that not all (and very commonly used) DRMs support this approach at present  -for instance Widevine does not support this across the whole client eco-system and FairPlay does not support this at all (yet).

My issue is really about the intent of the spec to preclude the possibility of 'leaf' keys being alternatively considered as 'individual' keys on a per DRM system basis so that it would be possible to deploy key rotation using the standard approach that suits each DRM best.
I don't think that the consequence that a license may have to be acquired on each rotation (i.e use of rotating individual keys) would necessarily mean rendering errors. In fact, each DRM that I have experience with has specific solutions for that problem that can be implemented outside of CPIX.

If via CPIX, it was possible to signal that a key was a 'leaf' key only within the context of specific DRM systemId(s) - then I think we would have the flexibility to cover all use-cases...

Let me know what you think.

**Comment by lpiron** [comment]
DRMSystem elements are referencing the content key. It seems difficult to have an attribute of a content key that can only apply to some DRM systems without breaking the model. That would be a major change.
A simple option for doing this is to create 2 documents, one with key hierarchy and one without.

**Comment by karlg-arris** [comment]
Ok - that seems rather awkward to explain to packager vendors  - however it is an option.

Thanks

**Comment by lpiron** [comment]
If there is no additional comment before tomorrow, I propose to close this bug with "no action".
