### ISSUE TITLE
CPIX 2.1  key usage rules

### ISSUE THREAD

**Issue by karlg-arris** [Dash-Industry-Forum/CPIX#45]
Hello,

Referring to Section 5.2.12.3 LabelFilter Element

The binding of key usage rules to specific track types has been a re-occurring problem for us  - particularly with respect to integration with 3rd party vendors.

In the latest spec update it is still unclear as to how exactly this can be achieved or defined.

Right now the following aspects need some clarity I think

1.)What is the exact difference between the label/labelfilter and the indentedTrackType attribute?
2.)I think it needs to be clear that if the binding of keys to specific media tracks to specific keys is to be by established convention, that this is the ONLY method currently provided by CPIX  - i.e there is no implicit or inferred alternative
3.)Maybe my understanding is flawed  - but if the possible values for intendedTrackType are not pre-agreed how can it function as defined?

**Comment by sandersaares** [comment]
`intendedTrackType` is metadata that says "business logic uses the name X for the tracks that match this rule". It has no function in defining what keys are matched to what tracks, it simply acts as a label to allow business logic to say "use 'SD' keys" and then a CPIX processor can find the rules that say they are for 'SD'

Labels are a generic mechanism for pre-agreed filters. Maybe there is a previous agreement (outside a CPIX document and the API that uses it) that "blue tracks" are encrypted with key X and "green tracks" are encrypted with key Y. The labels can be used to identify the suitable tracks (without expressing the specifics of the agreement itself).

I do not understand point 2 in the issue - please clarify what you mean.

**Comment by karlg-arris** [comment]
On point 2.) What I think needs clarity (one way or the other) would be how to handle and signal some specific key usage scenarios thats seem to crop up a lot due to rights holder and DRM requirements

1.)How via CPIX can we explicitly state that a key is only valid for audio encryption (and conversely with video)
2.)How via CPIX can we explicitly state that a key can only be used for encrypting HD, 4K, HDR ..etc

I realise that trying to define what something like '4K' actually means might be an issue, however, even if the answer is that these use-cases cannot (or should not) be explicitly covered by CPIX, then I think this point should be clarified somewhere.   

Otherwise we end up with implementations that are based on individual interpretation or inferences and have a headache between vendors.

**Comment by sandersaares** [comment]
Policies such as this are the input to generating CPIX documents and CPIX itself is not intended to express them, merely the resulting arrangement of keys after applying such policy. I therefore think this lies out of scope of CPIX.

I can certainly agree that such agreements can be a source of confusion and having some strict definitions might help but it does not seem very actionable to me. This type of thing is always very case-specific and I would be very hesitant in approaching any attempt to nail it down in a specification (it is unlikely that one could achieve a format that can accurately represent the various freeform statements that contracts between cooperating companies can have here).

**Comment by karlg-arris** [comment]
@sandersaares   Thank you for the clarifications.  

Please consider this as resolved.

**Comment by karlg-arris** [comment]
@lpiron Yes, personally I think a clarification along the lines stated here would be a very helpful addition to the specification.

**Comment by lpiron** [comment]
I will merge the proposed change tomorrow.

**Comment by lpiron** [comment]
Merge done
