### ISSUE TITLE
Recommendations for Low-Latency Live

### ISSUE THREAD

**Issue by tinskip** [Dash-Industry-Forum/CPIX#48]
Make some recommendations for low-latency live protected content, focus on minimizing startup time and lag-behind-live.

(could not figure out where to put this defect).

**Comment by sandersaares** [comment]
Related https://github.com/Dash-Industry-Forum/DASH-IF-IOP/issues/338

**Comment by lpiron** [comment]
Closing as there is an issue under IOP
