### ISSUE TITLE
Contents of ContentProtectionData field

### ISSUE THREAD

**Issue by arjen4157** [Dash-Industry-Forum/CPIX#50]
It is unclear whether the ContentProtection Element is part of the signaled data in the ContentProtectonData field. The specification seems to imply that this is not the case, but looking at the example clearKey.xml file it is part of the ContentProtectionData.

I think it should be present; since it includes the @schemeiduri, @value. It also allows us to e.g. define an additional namespace. E.g. in the case of:

--ContentProtection
  xmlns:mspr="urn:microsoft:playready"
  schemeIdUri="urn:uuid:9A04F079-9840-4286-AB92-E65BE0885F95"
  value="MSPR 2.0"--
  --mspr:pro--
    base64 pro header
  --mspr:pro
--ContentProtection

**Comment by sgrelet** [comment]
This has been discussed in #31.

**Comment by lpiron** [comment]
If there is no additional comment before tomorrow, I propose to close this bug with "no action".

**Comment by arjen4157** [comment]
I would like to make a case for including the ContentProtection element in the ContentProtectionData field.

From 23009-1:2014: 'For the element ContentProtection the @schemeIdUri attribute is used to identify a content protection scheme. This attribute should provide sufficient information, possibly in conjunction with the @value and/or extension attributes and elements, such as the DRM system(s), encryption algorithm(s), and key distribution scheme(s) employed, to enable a client to determine whether it can possibly play the protected content. The ContentProtection element can be extended in a separate namespace to provide information specific to the content protection scheme (e.g., particular key management systems or encryption methods).'.

And from https://dashif.org/identifiers/protection/

'it is recommended that the @value field is the name of the company system and client version. If used, this can help the client to determine if the current DRM client can play the content. If used differently, the providers of the DRM system are encouraged to document the alternative usage of the @value field.'

**Comment by lpiron** [comment]
For the namespace extension, this can done as described in #31. 
The schemeIdUri attribute is fully defined by the specification and therefore it is not needed to have it defined in every CPIX document.
For the @value, there was no comment on #31 stating that it is not used. Do you have examples where it is used ?

**Comment by arjen4157** [comment]
According to DASH-AVC/264 [3], it is recommended that the @value field is the name of the company system and client version.

If the full element is included I can simply implement this IOP's recommendation. Without it I can't.

-- A small list of where it is used:

Verimatrix ViewRight Web / DASH @value= “Verimatrix VCAS for DASH, ViewRightWeb VV.vv” (VV.vv will be the version number)This is the name of the company system and client version as recommended in DASH-AVC/264. If used, this can help the client to determine if the current DRM client can play the content.

--

SecureMedia, ArrisThe UUID of @schemeIdURIis a version 4 UUID as per RFC 4122.@valueshall be as follows: “Arris SecureMedia version XXXXXXX”XXXXXX will be specified in documentation associated with a particular version of the product. 

--

DigiCAP SmartXess for DASH @value “CA/DRM_NAME VERSION” (CA 1.0, DRM+ 2.0)

--

Another example from https://docs.microsoft.com/en-us/playready/specifications/mpeg-dash-playready

It is RECOMMENDED to include the @value attribute with name and version “MSPR 2.0”.

--

**Comment by arjen4157** [comment]
With reference to https://github.com/Dash-Industry-Forum/CPIX/issues/51 (Protection Scheme Signaling in MPD) the signaling of the protection scheme can be done by adding an additional ContentProtection element:

_xml_ContentProtection
        schemeIdUri="urn:mpeg:dash:mp4protection:2011"
        value="cbcs"
        cenc:default_KID="00000000-0000-0000-0000-000000000002"
_xml_/ContentProtection>

**Comment by lpiron** [comment]
The proposed solution for #56 is accepted, it is taken as a resolution for this bug.
