### ISSUE TITLE
Protection scheme in Content Key

### ISSUE THREAD

**Issue by psimax** [Dash-Industry-Forum/CPIX#51]
Encryptor expects that protection data (PSSH) that is generated by DRM system will contain either key algorithm (PlayReady) or protection scheme (Widevine). DRM System also needs to know the key type to create a valid license if it won't be specified in the license request.

It is not clear if Algorithm field of a <ContentKey> element can be used to signal from Encryptor to DRM System in which mode (CTR vs CBC) Content Key will be used.
As it said in the document: 

>  Algorithm (O, xs:ID)
>  This is an attribute inherited from [RFC6039] and made optional in this specification.

of type "xs:anyURI", but refers to [xmlenc table](https://www.w3.org/TR/2002/REC-xmlenc-core-20021210/Overview.html#sec-Algorithms).

The Algorithm field can be used for this purpose, but _xmlenc_ scheme is limited and doesn't have ctr mode. Something like _http://www.w3.org/2001/04/xmlenc#**aes128-ctr**_ can be used but makes document less transparent.

**Comment by KilroyHughes** [comment]
I don't have a specific recommendation for CPIX, but a couple considerations:
1. Common Encryption defines a 4 character code for each encryption algorithm. There is more to the algorithm that the AES-128 block chaining method (cbc or counter mode), e.g. clear/encrypted byte range mapping to NAL structures, constant IV vs. per sample IV, handling of partial cipher blocks, pattern encryption, etc. For instance, the use of AES CBC or CTR mode for "clear key" envelope encryption (e.g. in HLS) is entirely different. 4CC codes only apply within the scope of Common Encryption.
2. DASH defined a Content Protection Descriptor URI for ISOMedia Common Encryption with @value of the scheme 4CC and elements or attributes for KID and an encoded PSSH box. Maybe that would be useful.

**Comment by lpiron** [comment]
One option could then be to attach to the key a DRMSystem element that contains the ContentProtection element identified by urn:mpeg:dash:mp4protection:2011

**Comment by lpiron** [comment]
Yep, indeed, not a solution

**Comment by lpiron** [comment]
During the call, some comments were made to the proposed solution. The encryption method of content is not an attribute of the key but of content itself. It is then limiting the possible use of the content key if attaching an attribute. The recommendation is to use DRM information exchanged as opaque data if this encryption method is needed for a specific DRM.

**Comment by psimax** [comment]
I agree that the encryption method is more applicable to content. Will it be a part of the exchange protocol?

**Comment by lpiron** [comment]
This is an option. Please open a bug on the exchange protocol repository for this. I will then close this one with no action.

**Comment by wilevers-usp** [comment]
Reading this, it is still unclear to me how to signal the cenc scheme type (`cenc', `cbc1', `cens' or 'cbcs') in a CPIX document:

* If ContentKey's `algorithm' attribute is supposed to be used, then what are the URNs corresponding to these scheme types? What is the default if the `algorithm' attribute is not present?
*  What if I'd like to specify a different scheme type (for the same KID) that depends on the playout format, say `cenc' for DASH or and `cbcs' HLS?

Can anyone shed some light on this? Thanks!

**Comment by lpiron** [comment]
This is not expected in the CPIX document. The method for encrypting content is not really a relevant attribute of the key, this is an attibute of content. Widevine has it (protection_scheme) but it is optional and will be deprecated in favor of signalling from the content. PlayReady has the ALGID but also optional.

**Comment by wilevers-usp** [comment]
@lpiron: thanks for your answer. Obviously, for content that's already encrypted, the scheme type is an attribute of the content. However, that does not apply to content that is yet to be encrypted.

For encrypting content, we'd like to use CPIX to specify which scheme type to use, just as we can for the content encryption key and the IV. If the _algorithm_ attribute is the wrong place for this, we will need to use a vendor-specific attribute. We will probably call it _schemeType_; possible values are _cenc_, _cbc1_, _cens_ and _cbcs_.

**Comment by lpiron** [comment]
You want the DRM system to indicate to the packager which encryption mode for the content to use if I understand correctly. That goes beyond CPIX scope which is about exchanging content key and DRM information between entities. Having your extension is maybe the best.

**Comment by sandersaares** [comment]
Well, it is true that the PSSH boxes of some popular DRM technologies include this field. The field is optional but not optional in the sense of "defaults to not defined" but rather "defaults to cenc". In practice, we find some players will fail to play back if this field in the PSSH is not set right.

This means that the same DRM system needs to be signaled in different ways depending on the encryption mode. But oh no! CPIX currently just has one signaling block per content key per DRM system!

Therefore, PSSH signaling present in a CPIX document likely already contains an implicit assumption of the encryption mode. This makes it difficult to use CPIX documents in combination with encryption modes, as you might not know what is used in the PSSH.

Signaling the encryption mode in a standard CPIX parameter might be beneficial.

But it is also not as simple as that, either. It is perfectly valid and even common to encrypt the same content with *multiple* encryption modes! Should this be done as a single CPIX document containing signaling for both modes? Or multiple CPIX documents, one for each mode?

I dislike the combinatorics that might result from adding a layer of indirection to support mutliple encryption modes for the same content key in a single CPIX document. However, there seems to be some merit in explicitly marking the encryption mode of a content key, due to the fact that PSSHs already implicitly contain this data. If CPIX lacks this support, there is a (slightly) greater risk of the PSSH of one encryption mode being combined with content with another encryption mode.

It is a messy topic, no doubt about it. But that's DRM for you!

**Comment by RufaelDev** [comment]
signalling encryption mode in pssh is also using proprietary/private fields. There is no standard 
way to signal the encryption scheme inside the pssh box. 
It is different for different systems, See the definition of pssh in the cenc spec
 
from ISO/IEC common encryption: 
pssh box:
This box contains information needed by a Content Protection System to play back the content. The data format is specified by the system identified by the ‘pssh’ parameter SystemID, and is considered opaque for the purposes of this specification. 
aligned(8) class ProtectionSystemSpecificHeaderBox extends FullBox(‘pssh’, version, flags=0) 
{ 
	unsigned int(8)[16]		SystemID;
	if (version > 0) 
	{ 
		unsigned int(32)		KID_count; 
		{ 
		unsigned int(8)[16]	KID; 
		} [KID_count]; 
	} 
	unsigned int(32)				DataSize; 
	unsigned int(8)[DataSize]	Data;
}
there is no standardized field for signalling the encryption scheme, this is all private data so i see no conflict when signalling this in CPIX

**Comment by mstattma** [comment]
I'd like to propose to add the commonEncryptionScheme attribute (also) to the pssh data. And in addition to enable the packager to reuse the same key for cenc as well as cbcs modes. I'm aware that certain DRM schemes suffer from a weakened protection when keys are reused like that, but there are valid use cases under certain conditions (e..g when only DRM schemes are used which don't suffer that limitation) which shouldn't be excluded. The current approach makes it impossible to reuse keys, however I believe CPIX shouldn't limit usability but rather remain neutral to such issues.

**Comment by sandersaares** [comment]
The current version of CPIX does support using the same keys with multiple protection schemes, just not in a single CPIX document. Nothing prevents one from making two CPIX documents differing only by the protection scheme.

At minimum, we should outline this possibility in CPIX to avoid creating the impression that CPIX restricts the choice of protection schemes - as you rightly say, there are perfectly valid scenarios for encrypting with multiple schemes.

**Comment by mstattma** [comment]
That's a viable workaround, closing issue.

**Comment by lpiron** [comment]
closing as PR #81 is merged
