### ISSUE TITLE
Add human-readable DRM name for DASH ContentProtection

### ISSUE THREAD

**Issue by TanguyPerson** [Dash-Industry-Forum/CPIX#56]
DASH-IF IOP requests that the DRM name and version be provided in addition to its system ID.
It is done in the MPD through the `@name` attribute of the `ContentProtection`element.

It seems useful at least for debugging,  but also maybe to provide end-user with a gentle DRM name.

In DASH-IF IOP v4.2, §7.7.2
> The `@value` attribute of the `ContentProtection` Descriptor for UUID Scheme 
> SHOULD contain the DRM system and version in a human readable form. 

Example from DASH IOP v4.2, §7.7.2
`
<ContentProtection schemeIdUri=”urn:uuid:d0ee2730-09b5-459f-8452-200e52b37567”
    value=”Acme DRM 2.0”>
`

I didn't find a way for CPIX document to provide that name. `ContentProtectionData` allows to provide the content of `ContentProtection` element but not to set attributes.

Proposal:
- adding an `@name` attribute to `DRMSystem` element.
- that new attribute is a string and is optional
- description: human-readable name and version of the DRM system. This value can be used in DASH manifest as the value for `@name` attribute of `ContentProtection` element.

**Comment by lpiron** [comment]
This has been (somehow) reported in #50 and #31.
We didn't come with a solution and in #31 this was not seen as a bug. 
Now I do not have problem with the proposed optional attribute and indeed having a human readable identifier of the DRM can help debugging.
We have aDASH-IF group call on Wednesday July 11, 10:00 AM Pacific time where this can be discussed.

**Comment by lpiron** [comment]
Please have a look at the proposed resolution (implementing the solution above). If there are no comments before Wednesday EOB, I will merge.

**Comment by TanguyPerson** [comment]
The patch looks OK to me
