### ISSUE TITLE
Provide HDCP level guidance

### ISSUE THREAD

**Issue by TanguyPerson** [Dash-Industry-Forum/CPIX#57]
Some DRM can include HDCP level requirements (at least PlayReady I think). And some protocols can include signalling HDCP level (e.g. HLS through the `@HDCP-LEVEL@` attribute of the `#EXT-X-STREAM-INF` tag of Master Playlist).

So CPIX Document should provide HDCP level guidance to allow proper signalling.

Disclaimer: I am no HDCP expert.
Note: For HLS, it can't be done with current `HLSSignalingData` element

Proposition:
- a new attribute `@hdcpLevel` is added to `ContentKey` element
- the attribute is optional string
- missing attribute, empty string value or value "none" mean that there is no HDCP level requirement
- other value should be defined, matching HDCP levels (reference required), e.g. "TYPE-0", "TYPE-1"
- if value is unknown, that part of the document should be considered as invalid and the key should not be used
- it 's up to the application to match these HDCP values to OTT protocol-specific signaling (if any)

**Comment by lpiron** [comment]
Not sure this should be part of a CPIX document as this is not related to a DRM or a content key but this is an attribute of the content.

**Comment by TanguyPerson** [comment]
In a way, I agree : a content could be streamed in clear but require HDCP between decoder and display. If so, HDCP doesn't protect much the content...

So it seems to me that DRM and HDCP policies need to be tightly related, as content protection level is the weakeast of DRM and HDCP.

Besides, 
- PlayReady allows to include HDCP requirements in addition to content encryption itself
- [HLS RFC](https://tools.ietf.org/html/draft-pantos-hls-rfc8216bis-02#section-4.4.4.2) states a relationship between HDCP and DRMat least for per-track encryption case:
>  Encrypted Variant Streams with different HDCP levels SHOULD use different media encryption keys.

**Comment by lpiron** [comment]
We discussed this bug during our call. It is accepted that having such information (not limited to HDCP level) exchanged may have some value but it deserves a new specification. This specification should consider how to define content usage rules that maps a "business contract" defined between a content provider and the operator. Content usage rules can cover, and are not limited to, HDCP, DTCP, which version of DRM, hardware support, recording permission, time shift and start-over permission .... No-one in the call is willing to start such specification.
