### ISSUE TITLE
We need to publish a fixed XSD

### ISSUE THREAD

**Issue by sandersaares** [Dash-Industry-Forum/CPIX#66]
https://github.com/Dash-Industry-Forum/CPIX/commit/5308a0e4bea68180c407f68fc3aaacfaea7b98c6 fixed a defect in the XSD for HLS playlist types. We should publish the fix before someone implements the broken XSD!

Right now the broken XSD is published on dashif.org.

**Comment by lpiron** [comment]
In fact, dashif.org is referencing CPIX 2.1 that does not have the fix. The fix on dashif.org should maybe to stop referencing the versions and only give a link to the living version of the document on the GitHub repository.

**Comment by lpiron** [comment]
Publication is done
