### ISSUE TITLE
Make it clear that version 2.1 of the spec is not changing anymore

### ISSUE THREAD

**Issue by jjauch** [Dash-Industry-Forum/CPIX#67]
The DASH-IF website mentions CPIX 2.1 as the latest version:
https://dashif.org/guidelines/

However, the [PDF document](https://dashif.org/docs/CPIX2.1/PDF/Index.pdf) that is linked on the website shows the subtitle: *Living Document, 16 July 2018*

This seems to suggest that this is not an immutable, released version, but something that is still being developed. This might lead developers to revert to v2.0 as the seemingly latest published version.

A better subtitle would be *Version 2.1, 16 July 2018*

**Comment by lpiron** [comment]
There were some bugs opened on 2.1 (on HLS support) and the version on dashif.org will be updated.
2.2 is created with these changes. See pull requests #64 , #65 and #68

**Comment by lpiron** [comment]
Publication is done
