### ISSUE TITLE
No signalling for content key generation "mode"

### ISSUE THREAD

**Issue by kkwiatek1606** [Dash-Industry-Forum/CPIX#69]
In "Encryptor Consumer" workflow, in some user cases DRM System supports multiple modes of content key generation, for example:
- "Stateful" mode where keys are generated randomly and stored in DRM System database
- "Stateless" mode where keys are derived from key seeds, and not stored.
- Other content key generation modes, for example based on key derivation from different seeds
In these cases, to be able to support both modes, the Encryptor must signal the "mode".

Currently, CPIX spec doesn't support such signalling or doesn't give any recommendation in such scenario's.

One option could be to use "pskc:KeyProfileId" from RFC6030 for this purpose.

**Comment by lpiron** [comment]
This is not considered to be in the scope of the CPIX document. how content keys are generated and what is life cycle depends on where the CPIX document is used.

**Comment by lpiron** [comment]
Closing as it is sleeping for few months with no action expected
