### ISSUE TITLE
Allow DRM system to overwrite content key IDs

### ISSUE THREAD

**Issue by kkwiatek1606** [Dash-Industry-Forum/CPIX#70]
In "Ecryptor Consumer" workflow, it is assumed that Ecryptor generates and provides content key ID (`kid`).
This ID is referenced in `ContentKeyUsageRule` and `DRMSystem` elements.

In some cases, for example when content key is derived from key seed, in stateless system, the generation of `kid` is partially deterministic and `kid` itself may contain data required to re-generate the content key. 
For that reason `kid` has to be generated by DRM system and provided to Encryptor, alongside the content key.

SPEKE provides a solution, by allowing to overwrite `kid` by DRM system. This may be fine when CPIX document contains one `ContentKey` element, but it will not work with multiple keys - there is not mapping current <-> new `kid`.

Therefore possible solution could be:
- To return (optionally) a new overwriting `kid` as additional element in `ContentKey`.
- To return (optionally) a new element under `CPIX` with mapping  current <-> new for all `kid` values in the document.

**Comment by lpiron** [comment]
We discussed this bug during our last call. It is not clear the particular implementation you have in mind. Can you clarify by providing a drawing with a workflow ? 
Also, if you are DASH-IF member, I encourage you to join our next call on May 1st.

**Comment by kkwiatek1606** [comment]
![Encryptor - DRM System Workflow](https://user-images.githubusercontent.com/26602036/56814822-410bd180-6840-11e9-8ef9-71a7889f050b.png)
1. Encryptor provides an incomplete document, possibly with multiple key IDs (kid) for example for different tracks (HD, SD etc.).
2a-d. DRM System internally generates Key ID (`kid'`) and Content Key, using Key Derivation service. The new Key ID is meant to be used by a packager.
3. DRM System prepares and returns complete document with Content Key data and DRM signaling (PSSH box, ContentProtectionData)
**The problem is: how to handle newly generated `kid'`?** 

Yes, I'm a member of DASH-IF (Irdeto) and I will join a call on 15 May.

**Comment by lpiron** [comment]
Closing as it is sleeping for few months
