### ISSUE TITLE
Clarify encoding to use for explicitIV

### ISSUE THREAD

**Issue by karlg-arris** [Dash-Industry-Forum/CPIX#71]
Hi,

The encoding for AES keys is unambiguously defined in the relevant RFC referenced by CPIX spec, however there is, I believe ambiguity, concerning the explictIV attribute - namely 

should it be UTF-8 or binary format (as per keys)?

**Comment by sandersaares** [comment]
Could you explain in detail the nature of the ambiguity? What is the alternative besides binary? It does not immediately pop into my mind what you mean by a UTF-8 encoding for IVs (which I think of as 128 bits of binary data).

The intent is certainly to just do `base64encode(byte[16])`. Can you suggest a better wording for the relevant definition in the spec that would remove this ambiguity?

> explicitIV (O, xs:base64binary)
>
> The IV to use when solution-specific logic requires a single explicit IV to be associated with a Content Key.
> 
> The primary use case is to enable the use of DRM systems that associate a single IV with each Content Key and whose DRM client implementations are unable to extract the IV from the content, requiring the license server to deliver the IV together with the Content Key upon request. A CPIX document can be used to supply the Content Key and IV together to the license server.
> 
> Use of this attribute is not recommended except for compatibility with such DRM systems. Even if present in a CPIX document, the attribute should be ignored if solution-specific logic does not require it to be used

**Comment by karlg-arris** [comment]
@sandersaares 
Hi  - let me first correct the semantics of the example I provided.

it should have been encoded binary format vs hexidecimal notation 

e.g for IV 83C7E01B57484906A62CD74817F90491

Either
echo '83C7E01B57484906A62CD74817F90491' | base64
ODNDN0UwMUI1NzQ4NDkwNkE2MkNENzQ4MTdGOTA0OTEK

OR
echo '83C7E01B57484906A62CD74817F90491' | xxd -r -p | base64
g8fgG1dISQamLNdIF/kEkQ==

Let me say that I certainly agree that binary seems more obvious, however, the reason I raised this ticket is that, in practice, we have seen packagers expect both formatting types...

Thanks

**Comment by sandersaares** [comment]
Thank you for the clarification - I understand what you mean now. Yeah, we can clarify this to remove the amgibuity. How does this wording sound:

> The value consists of a 128-bit IV in binary format, base64-encoded.

**Comment by sandersaares** [comment]
FYI, the CPIX validator at https://cpix-validator.azurewebsites.net/ has been upgraded to the latest version of the CPIX library, so it will now check explicitIV to validate it appears to have the right data (at least, it will check the number of bytes within, which will be too much if it is a hex-format value).

**Comment by karlg-arris** [comment]
The wording sounds ok to me,

Thanks!

**Comment by lpiron** [comment]
If there are no additional comments before the end of the week, I will merge the PR and close this issue next Monday.

**Comment by lpiron** [comment]
Merge done
