### ISSUE TITLE
Not possible to ingest multiple keys for the same rotation period

### ISSUE THREAD

**Issue by karlg-arris** [Dash-Industry-Forum/CPIX#76]
Hi,

I am trying to create sample documents that show key rotation for use-cases in which keys are rotated for more than one media track type at a time.

I cannot validate my examples against the schema because I cannot have more than one KeyPeriodFilter referencing the same ContentKeyPeriod.

For example:

<cpix:CPIX xmlns:xenc="http://www.w3.org/2001/04/xmlenc#" xmlns:pskc="urn:ietf:params:xml:ns:keyprov:pskc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instanc
    <cpix:ContentKeyList>
        <cpix:ContentKey kid="7ce7f10d-a91b-41b9-b331-7999fd1abf4c" explicitIV="f45bcebb-f0df-4a34-bf4e-c24edfcf6289" id="video">
            <cpix:Data>
                <pskc:Secret> <pskc:PlainValue>s/zSNTG4TR2jY04srqSqFQ==</pskc:PlainValue> </pskc:Secret>
            </cpix:Data>
        </cpix:ContentKey>
        <cpix:ContentKey kid="988395ce-667a-443a-b9cc-58ad7875a687" explicitIV="6f411e73-eb4a-4373-8757-a70b624c278c" id="audio">
            <cpix:Data>
                <pskc:Secret> <pskc:PlainValue>B9mye8sHQJSOhOkbpKKpNg==</pskc:PlainValue> </pskc:Secret>
            </cpix:Data>
        </cpix:ContentKey>
    </cpix:ContentKeyList>
     <cpix:ContentKeyPeriodList>
        <cpix:ContentKeyPeriod id="now" index="1"></cpix:ContentKeyPeriod>
    </cpix:ContentKeyPeriodList>
    <cpix:ContentKeyUsageRuleList>
        <cpix:ContentKeyUsageRule kid="7ce7f10d-a91b-41b9-b331-7999fd1abf4c">
             <cpix:KeyPeriodFilter periodId="now"></cpix:KeyPeriodFilter>
             <cpix:VideoFilter></cpix:VideoFilter>
        </cpix:ContentKeyUsageRule>
        <cpix:ContentKeyUsageRule kid="988395ce-667a-443a-b9cc-58ad7875a687">
            <cpix:KeyPeriodFilter periodId="now"></cpix:KeyPeriodFilter>
            <cpix:AudioFilter></cpix:AudioFilter>
        </cpix:ContentKeyUsageRule>
    </cpix:ContentKeyUsageRuleList>
</cpix:CPIX>

In this case it seems like the schema definition is preventing me from legitimately binding both the audio key and the video key to the same period (by index).

In fact, it seems like the schema does not ever allow the intended relationship between ContentKey and ContentKeyPeriod due to the definition of both 'periodId' and 'Id' attributes as 'xs:ID'    - should 'periodId' be of type 'xs:IDREF'?

**Comment by sandersaares** [comment]
> In fact, it seems like the schema does not ever allow the intended relationship between ContentKey and ContentKeyPeriod due to the definition of both 'periodId' and 'Id' attributes as 'xs:ID' - should 'periodId' be of type 'xs:IDREF'?

At a glance, it sounds like this might indeed be the culprit here. Would you be willing to submit a PR that corrects the schema in this regard (and any others that prevent this scenario from working, should there be multiple defects involved)?

**Comment by karlg-arris** [comment]
@sandersaares  I submitted a pull request
