### ISSUE TITLE
BitrateFilter measurement unit not really suitable for audio

### ISSUE THREAD

**Issue by nicoweilelemental** [Dash-Industry-Forum/CPIX#78]
minBitrate and maxBitrate are said to be expressed in Mb/s, but the sample https://github.com/Dash-Industry-Forum/cpix-test-vectors/blob/master/EvenMoreComplex.xml is using bits/s, which seems to be more suitable for audio renditions.

**Comment by sandersaares** [comment]
Agreed. I believe `Mb/s` is an error.

**Comment by lpiron** [comment]
Will be changed in b/s

**Comment by lpiron** [comment]
Corrected with PR #80. Closing
