### ISSUE TITLE
SPEKE/CPIX alignment points

### ISSUE THREAD

**Issue by nicoweilelemental** [Dash-Industry-Forum/CPIX#79]
Following the work item creation, AWS Elemental has reviewed the various CPIX-related points that were listed in the document with the objective of defining the scope of CPIX v2.3 and allow the removal of all custom namespaces added to CPIX documents by the SPEKE API:

**1/ Add equivalent elements to <speke:KeyFormat> and 
<speke:KeyFormatVersions> for HLS encryption**
This is actually not needed, as SPEKE-compliant packagers can now leverage the HLSSignalingData Element. If they need discrete values for KeyFormat and KeyFormatVersions, they should extract it from the HLSSignalingData Element after a base64 decoding operation.

**2/ Add an explicit versioning through the <CPIX@version> attribute**
This is still needed. The proposal is to add an optional 'version' attribute in the CPIX Element, as follows:

**_version_ (O, xs:string)**
Specifies a version for the CPIX document. The value shall reference a CPIX Guidelines published version and be structured as 'major_version.minor_version'. Example: '2.2'

**3/ Include the proposal for
<ContentKey@commonEncryptionScheme> or equivalent notion**
This is still needed. I believe this is covered in the issue #75 

**4/ Introduce a SPEKE profile in CPIX to facilitate long term evolutions and possibly allow other CPIX profiles to be introduced if necessary**
_Topics listed were: Summarize constraints on CPIX, Describe Content Key Encryption approach, Describe a reference approach for multiple encryption keys support, List mandatory elements expected in the CPIX documents_
We believe that this is not needed, as all the listed topics are already part of the SPEKE documentation , which will be updated soon to reflect the introduction of SPEKE v2 leveraging CPIX v2.3, and as it's not a good practice to duplicate the specification points. 
If a 'Profiles' section would still need to be added in the CPIX specification, then we would like SPEKE to be just listed in the section, with a link to its [documentation](https://docs.aws.amazon.com/speke/latest/documentation/speke-api-specification.html).

**Comment by RufaelDev** [comment]
@nicoweilelemental thanks for sharing your analysis, one other good thing to document would be how the version number would be used by a client, would a legacy client fail in case newer CPIX document are retrieved, or would there be other recommended behavior ? Not everything has to be specified in detail, but it might be good to say something about the versioning field usage when it becomes optional/mandatory.

**Comment by nicoweilelemental** [comment]
I think 4 different cases can happen:

**1/ Old client & non-versioned CPIX**: this is the current behavior, unknown elements and attributes are ignored
=> best effort result

**2/ Old client & versioned CPIX**: the CPIX@version attribute is ignored, as other unknown CPIX elements and attributes
=> best effort result

**3/ 2.3+ client & non-versioned CPIX**: the CPIX version should be inferior to 2.3, so in theory the client should support it
=> best effort result

**4/ 2.3+ client & versioned CPIX**: the client can easily determine if it supports the feature set of a specific CPIX version.
If not, it could either 
=> process only the understood elements and attributes (best effort result)
=> return an error as defined by the API used for the CPIX document exchange

In the SPEKE v2.0 context, the encryptor initiating the request knows which version of CPIX it needs. If the DRM service doesn't support this specific CPIX version, it should return an error with an explicit description.

In a different API context not specifying the expected behavior, the best effort approach would have to be used.

So my recommendation is to keep the current best effort approach as the default, and say that in case the API has got a more restrictive policy, the client needs to respect it.

**Comment by lpiron** [comment]
PR merged, closing the bug

**Comment by karlg-arris** [comment]
@nicoweilelemental 
Hi,
Do you have a rough time estimate for when the V2 SPEKE/CPIX 2.3 documentation will be published?

**Comment by nicoweilelemental** [comment]
CPIX 2.3 is published https://dashif-documents.azurewebsites.net/Cpix/master/Cpix.html
SPEKE v2 doc will be provided to SPEKE partners in Q4, and generally available in Q1 2021.
