### ISSUE TITLE
Clarify KID string representation

### ISSUE THREAD

**Issue by sergiofagostinho** [Dash-Industry-Forum/CPIX#83]
Hi,

Following up the CPIX 2.3 draft spec and #71, I think the same ambiguity applies to the `kid` field (`xs:string`). Depending on the implementation, a Key Id might be represented as a UUID, Hexadecimal, or Base64, which may lead to incompatible implementations.

**Comment by lpiron** [comment]
We should follow IOP recommendation for been consistent and recommend UUID.

**Comment by lpiron** [comment]
Pull request merged
