### ISSUE TITLE
Signaling for W3C Clear Key

### ISSUE THREAD

**Issue by nicoweilelemental** [Dash-Industry-Forum/CPIX#87]
Looking at sections 14 & 15 of https://dashif-documents.azurewebsites.net/Guidelines-Security/master/Guidelines-Security.html it looks like a W3C Clear Key can be signaled in the manifest with multiple <dashif:laurl> or <dashif:authzurl> tags, but I don't see in CPIX where we carry this information. Are we missing some CPIX signaling for this use case?

**Comment by sandersaares** [comment]
All the `<dashif:xxx>` elements are children of `<ContentProtection>` and can therefore be signaled in the CPIX `DRMSystem/ContentProtectionData` element.

**Comment by lpiron** [comment]
Pull request merged
