### ISSUE TITLE
KID mandatory or optional in ContentKey

### ISSUE THREAD

**Issue by lpiron** [Dash-Industry-Forum/CPIX#88]
There can be use cases where a packager is requested to create content having only a contentID. When requesting a content key, it will create a CPIX document but does not want to create kid.
- It could be the case that the request for creating content is a second attend following quality control that were not good, hence the packager will provide the contentID and the key server will look for the associated content keys that have already been created and possibly already used somewhere else in the system.
- It could be the case that several transcoders/packagers work in parallel on the same content, hence, packagers cannot be the source of the kid.
Solving these cases can be done by making the kid optional under the ContentKey element.

**Comment by sandersaares** [comment]
IMO this would be scope creep. CPIX was always intended to represent key packages, transmitting a set of keys + metadata from point A to point B.

A request for keys is not a key package. Implementations should not be using CPIX for *requesting* keys.

**Comment by lpiron** [comment]
Closed with no changes. There are options by allowing the key server to overwrite the kid.
