### ISSUE TITLE
Clarification on DRMSystem.PSSH vs DRMSystem.ContentProtectionData

### ISSUE THREAD

**Issue by nicoweilelemental** [Dash-Industry-Forum/CPIX#96]
As we can find PSSH values in both DRMSystem.PSSH and DRMSystem.ContentProtectionData elements, I'd like to ask if there is a valid use case for finding PSSH data in both elements, but with different values. It sounds like not, and that it should trigger an error in the SPEKE v2 spec.

**Comment by nicoweilelemental** [comment]
Following our discussion today:
- if there is a duplicate of the PSSH information in both places, the value should be the same. No use case is identified for a different approach
- DRMSystem.PSSH should be mandatory when the segments container is ISO-BMFF: currently CPIX says in section 5.2.7 "This element has meaning only when the media content is in the ISOBMFF format." It should probably add "In such a case, this is a mandatory attribute". I will also put an equivalent requirement in the SPEKE v2 spec.

**Comment by lpiron** [comment]
I will implement this clarification for the ISOBMFF format is there is no objection by the end of the week.

**Comment by lpiron** [comment]
Implemented in the text.
