### ISSUE TITLE
Way to specify the HLS encryption method in ContentKey element

### ISSUE THREAD

**Issue by sanao** [Dash-Industry-Forum/CPIX#97]
Since CPIX 2.1, the HLS signaling is specified in `HLSSignalingData` element and must contains the encryption method (AES-128 or SAMPLE-AES). Since CPIX 2.3, attribute `commonEncryptionScheme` was added to `ContentKey` element but is dedicated to DASH (only CENC scheme are allowed).

From packager side, it don't know which encryption method must be used for the media segment without parsing the `HLSSignalingData` value (which may contains some extra proprietary information). So, I suggest to use the `cbc1` value in `commonEncryptionScheme` to specify encryption method AES-128 method and `cbcs` for encryption method SAMPLE-AES.

I know, `cbc1` is not really equivalent to AES-128 which encrypt all the media segment and not only the full sample, but, I assume it's an acceptable approximation.

And of course, the warning (https://dashif.org/docs/CPIX2.3/Cpix.html#element-attrdef-contentkey-commonencryptionscheme) about the consistency between `commonEncryptionScheme` and signaling in `DRMSystem` is still valid.

See above, an example of CPIX document with two keys:
* one used for AES-128 for video tracks lower to 4K and audio tracks
* other one for SAMPLE-AES for 4K resolutions
```
<cpix:CPIX xmlns:xenc="http://www.w3.org/2001/04/xmlenc#" xmlns:pskc="urn:ietf:params:xml:ns:keyprov:pskc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:cpix="urn:dashif:org:cpix" xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
  <cpix:ContentKeyList>
    <cpix:ContentKey kid="4f4ae514-4573-40ba-be3b-716649bad23b" commonEncryptionScheme="cbc1">
      <cpix:Data>
        <pskc:Secret>
          <pskc:PlainValue>fsAJZ3qMS0+V9dcCiaZHzg==</pskc:PlainValue>
        </pskc:Secret>
      </cpix:Data>
    </cpix:ContentKey>
    <cpix:ContentKey kid="1ef4c7f2-8e06-416a-97fe-cb5638490477" explicitIV="jrnbqEah4UHCVy1zOHQLHw==" commonEncryptionScheme="cbcs">
      <cpix:Data>
        <pskc:Secret>
          <pskc:PlainValue>McihFjkkl8L78Moz+Z+SNQ==</pskc:PlainValue>
        </pskc:Secret>
      </cpix:Data>
    </cpix:ContentKey>
  </cpix:ContentKeyList>
  <!-- System ID is for Anevia test -->
  <cpix:DRMSystemList>
    <!--
      Static Ext X Key for Apple HLS with AES-128.
      Base64 decoded value: #EXT-X-KEY:METHOD=AES-128,URI="https://misc.anevia.com/CPIX_2.0/key/key"
    -->
    <cpix:DRMSystem kid="4f4ae514-4573-40ba-be3b-716649bad23b" systemId="0bd3bd7e-0f43-4073-bf9f-f2fff467266c">
<cpix:HLSSignalingData>I0VYVC1YLUtFWTpNRVRIT0Q9QUVTLTEyOCxVUkk9Imh0dHBzOi8vbWlzYy5hbmV2aWEuY29tL0NQSVhfMi4wL2tleS9rZXki</cpix:HLSSignalingData>
    </cpix:DRMSystem>
    <!--
      Static Ext X Key for Apple HLS with SAMPLE-AES.
      Base64 decoded value: #EXT-X-KEY:METHOD=SAMPLE-AES,URI="https://misc.anevia.com/CPIX_2.0/key/sample_aes.key"
    -->
    <cpix:DRMSystem kid="1ef4c7f2-8e06-416a-97fe-cb5638490477" systemId="0bd3bd7e-0f43-4073-bf9f-f2fff467266c">
<cpix:HLSSignalingData>I0VYVC1YLUtFWTpNRVRIT0Q9U0FNUExFLUFFUyxVUkk9Imh0dHBzOi8vbWlzYy5hbmV2aWEuY29tL0NQSVhfMi4wL2tleS9zYW1wbGVfYWVzLmtleSI=</cpix:HLSSignalingData>
    </cpix:DRMSystem>
  </cpix:DRMSystemList>
  <cpix:ContentKeyUsageRuleList>
    <!-- Rule for video tracks lower to 4K -->
    <cpix:ContentKeyUsageRule kid="4f4ae514-4573-40ba-be3b-716649bad23b">
      <cpix:VideoFilter minPixels="0" maxPixels="8294399" />
    </cpix:ContentKeyUsageRule>
    <!-- Rule for 4K video tracks -->
    <cpix:ContentKeyUsageRule kid="1ef4c7f2-8e06-416a-97fe-cb5638490477">
      <cpix:VideoFilter minPixels="8294400" />
    </cpix:ContentKeyUsageRule>
    <cpix:ContentKeyUsageRule kid="4f4ae514-4573-40ba-be3b-716649bad23b">
      <cpix:AudioFilter />
    </cpix:ContentKeyUsageRule>
  </cpix:ContentKeyUsageRuleList>
</cpix:CPIX>
```

**Comment by lpiron** [comment]
We discussed this bug during our call yesterday.
We agreed to amend the text. The proposal is to introduce the HLS naming for encryption modes (AES-128, SAMPLE-AES) instead of giving different meanings of CENC ones if in the context of HLS.

**Comment by sanao** [comment]
@lpiron Any news about this proposal?

**Comment by lpiron** [comment]
There is a working draft that includes a proposal for this one. See at https://github.com/lpiron/CPIX . It does not give explicitly the values but refer to the CENC and HLS specifications. The schema is also updated for removing the constraint of the maximum length of 4 character for `@commonEncryptionScheme` as names are longer in HLS.
`@commonEncryptionScheme`
`The encryption scheme that the content key is intended to be used with. When present, the value shall be a 4-character Common Encryption protection scheme name as defined by MPEGCENC or one of the encryption method defined in HLS.`
