### ISSUE TITLE
HLSSignalingData element encoding type

### ISSUE THREAD

**Issue by nicoweilelemental** [Dash-Industry-Forum/CPIX#98]
5.2.8. HLSSignalingData Element currently says "The HLSSignalingData **allows carrying** base64 encoded text", which is a source of confusion as the encryptor can't predict what is the encoding type of the element value, base64 or something else.

We'd like to clarify this situation and update the spec to say that this element value shall be base64 encoded.

**Comment by lpiron** [comment]
Agree, will move to shall.
